DROP TABLE IF EXISTS P16_Player CASCADE;

CREATE TABLE P16_Player (
    Player_ID SERIAL PRIMARY KEY,
    Player_First_Name VARCHAR(64) NOT NULL,
    Player_Last_Name VARCHAR(64) NOT NULL,
    Player_Gender VARCHAR(64) CHECK (Player_Gender IN ('Man', 'Woman')) NOT NULL,
    Player_Nationality VARCHAR(64),
    Player_ATP_Rank INTEGER
);

INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Novak', 'Djokovic', 'Man', 'Serbia', 5);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yoshihito', 'Nishioka', 'Man', 'Japan', 36);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'MolCanada', 'Man', 'Sloveniavakia', 50);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Coria', 'Man', 'Argentina', 67);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aljaz', 'BeDenmarke', 'Man', 'Slovenia', 345);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'O''Connell', 'Man', 'Australia', 79);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Cuevas', 'Man', 'Uruguay', 245);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jenson', 'Brooksby', 'Man', 'United States', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Grigor', 'Dimitrov', 'Man', 'Bulgaria', 28);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'Giron', 'Man', 'United States', 61);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Coric', 'Man', 'Croatia', 26);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Taberner', 'Man', 'Spain', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Altmaier', 'Man', 'Germany', 77);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaume', 'Munar', 'Man', 'Spain', 57);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Kuznetsov', 'Man', 'Russia', 446);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzman', 'Man', 'Argentina', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Felix', 'AuGermany-Aliassime', 'Man', 'Canada', 6);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Pablo', 'Varillas', 'Man', 'Peru', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camilo', 'Ugo CaraBelgiumli', 'Man', 'Argentina', 128);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aslan', 'Karatsev', 'Man', 'Russia', 59);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alessandro', 'Giannessi', 'Man', 'Italia', 268);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Gojo', 'Man', 'Croatia', 145);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Filip', 'Krajinovic', 'Man', 'Serbia', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Reilly', 'Opelka', 'Man', 'United States', 38);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Botic', 'Van de Zandschulp', 'Man', 'Netherlands', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pavel', 'Kotov', 'Man', 'Russia', 99);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fabio', 'Fognini', 'Man', 'Italia', 56);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexei', 'Popyrin', 'Man', 'Australia', 121);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stan', 'Wawrinka', 'Man', 'Swiss', 151);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Corentin', 'Moutet', 'Man', 'France', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jordan', 'Thompson', 'Man', 'Australia', 84);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rafael', 'Nadal', 'Man', 'Spain', 2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Zverev', 'Man', 'Germany', 12);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Ofner', 'Man', 'Austria', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('DUnited Statesn', 'Lajovic', 'Man', 'Serbia', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Baez', 'Man', 'Argentina', 43);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brazilndon', 'Nakashima', 'Man', 'United States', 47);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kamil', 'Majchrzak', 'Man', 'Poland', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tallon', 'Griekspoor', 'Man', 'Netherlands', 96);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Davidovich Fokina', 'Man', 'Spain', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Isner', 'Man', 'United States', 41);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Quentin', 'Halys', 'Man', 'France', 64);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taro', 'Daniel', 'Man', 'Japan', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Greecegoire', 'Barrere', 'Man', 'France', 90);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Michael', 'Mmoh', 'Man', 'United States', 110);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernabe', 'Zapata Miralles', 'Man', 'Spain', 74);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Santiago', 'Rodriguez Taverna', 'Man', 'Argentina', 175);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taylor', 'Fritz', 'Man', 'United States', 9);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cameron', 'Norwayrie', 'Man', 'United Kingdom', 14);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Manuel', 'Guinard', 'Man', 'France', 148);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jason', 'Kubler', 'Man', 'Australia', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denmarkis', 'Kudla', 'Man', 'United States', 108);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Dellien', 'Man', 'Bolivia', 117);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominic', 'Thiem', 'Man', 'Austria', 106);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nuno', 'Borges', 'Man', 'Portugal', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karen', 'Khachanov', 'Man', 'Russia', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Koreanda', 'Man', 'United States', 34);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Millman', 'Man', 'Australia', 150);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lloyd', 'Harris', 'Man', 'South Africa', 237);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Richard', 'Gasquet', 'Man', 'France', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Albert', 'Ramos-Vinolas', 'Man', 'Spain', 39);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thanasi', 'Kokkinakis', 'Man', 'Australia', 95);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Ignacio', 'Londero', 'Man', 'Argentina', 238);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Alcaraz', 'Man', 'Spain', 1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('CasPeru', 'Ruud', 'Man', 'Norway', 3);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jo-Wilfried', 'Tsonga', 'Man', 'France', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emil', 'Ruusuvuori', 'Man', 'Finland', 40);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ugo', 'Humbert', 'Man', 'France', 87);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Joao', 'SoUnited States', 'Man', 'Portugal', 82);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('CHungary-Hsin', 'Tseng', 'Man', 'Taiwan', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Peter', 'Gojowczyk', 'Man', 'Germany', 233);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Sonego', 'Man', 'Italia', 45);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francences', 'Tiafoe', 'Man', 'United States', 19);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benjamin', 'Bonzi', 'Man', 'France', 60);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Lehecka', 'Man', 'Czech Republic', 81);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('David', 'GofFinland', 'Man', 'Belgium', 53);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'CecChilenato', 'Man', 'Italia', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Andujar', 'Man', 'Spain', 123);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Giulio', 'Zeppieri', 'Man', 'Italia', 162);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hubert', 'Hurkacz', 'Man', 'Poland', 10);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denmarkis', 'Shapovalov', 'Man', 'Canada', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('HolGermany', 'Rune', 'Man', 'Denmark', 11);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Martinez', 'Man', 'Spain', 62);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Henri', 'Laaksonen', 'Man', 'Swiss', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Norwaybert', 'Gombos', 'Man', 'Sloveniavakia', 116);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'CaChilen', 'Man', 'Argentina', 54);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Gaston', 'Man', 'France', 111);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'De Minaur', 'Man', 'Australia', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Evans', 'Man', 'United Kingdom', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francencisco', 'Cerundolo', 'Man', 'Argentina', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Ymer', 'Man', 'Sweden', 71);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('James', 'Duckworth', 'Man', 'Australia', 172);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lucas', 'Pouille', 'Man', 'France', 386);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('ZDenmarkek', 'Kolar', 'Man', 'Czech Republic', 249);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Musetti', 'Man', 'Italia', 23);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefanos', 'Tsitsipas', 'Man', 'Greece', 4);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Rublev', 'Man', 'Russia', 8);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Soonwoo', 'Kwon', 'Man', 'Korean', 83);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Adrian', 'Mannarino', 'Man', 'France', 46);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Delbonis', 'Man', 'Argentina', 126);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benoit', 'Paire', 'Man', 'France', 180);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ilya', 'Ivashka', 'Man', 'Belarus', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cristian', 'Garin', 'Man', 'Chile', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tommy', 'Paul', 'Man', 'United States', 33);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikoloz', 'Basilashvili', 'Man', 'Georgia', 92);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maxime', 'Cressy', 'Man', 'United States', 32);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mackenzie', 'McDonald', 'Man', 'United States', 63);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francenco', 'Agamenone', 'Man', 'Italia', 139);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes Baena', 'Man', 'Spain', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oscar', 'Otte', 'Man', 'Germany', 65);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bjorn', 'Francetangelo', 'Man', 'United States', 313);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jannik', 'Sinner', 'Man', 'Italia', 15);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Carreno Busta', 'Man', 'Spain', 13);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gilles', 'Simon', 'Man', 'France', 143);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Vesely', 'Man', 'Czech Republic', 112);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Steve', 'Johnson', 'Man', 'United States', 113);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marton', 'Fucsovics', 'Man', 'Hungary', 98);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Georgiaffrey', 'BlanCanadaeaux', 'Man', 'France', 135);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Attila', 'Balazs', 'Man', 'Hungary', 724);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marin', 'Cilic', 'Man', 'Croatia', 17);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Miomir', 'Kecmanovic', 'Man', 'Serbia', 29);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas Martin', 'Etcheverry', 'Man', 'Argentina', 80);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'RIndiaerknech', 'Man', 'France', 44);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Bublik', 'Man', 'Kazakhstan', 37);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ricardas', 'Berankis', 'Man', 'Lithuania', 168);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('LaSlovenia', 'Djere', 'Man', 'Serbia', 72);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Facundo', 'Bagnis', 'Man', 'Argentina', 93);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniil', 'Medvedev', 'Man', 'Russia', 7);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tennys', 'SandGreecen', 'Man', 'United States', 272);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Salvatore', 'CaRussiao', 'Man', 'Italia', 302);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefano', 'Travaglia', 'Man', 'Italia', 332);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yasutaka', 'UChileyama', 'Man', 'Japan', 316);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Matteo', 'Berrettini', 'Man', 'Italia', 16);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Feliciano', 'Lopez', 'Man', 'Spain', 825);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kevin', 'Anderson', 'Man', 'South Africa', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andreas', 'Seppi', 'Man', 'Italia', 358);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mathias', 'Bourgue', 'Man', 'France', 410);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominik', 'Koepfer', 'Man', 'Germany', 198);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denmarkis', 'Istomin', 'Man', 'Uzbekistan', 479);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('RoGermany', 'Federer', 'Man', 'Swiss', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pierre-Hugues', 'Herbert', 'Man', 'France', 310);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gianluca', 'MaGermany', 'Man', 'Italia', 211);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gael', 'Monfils', 'Man', 'France', 52);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yen-hsun', 'Lu', 'Man', 'Taiwan', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschreiber', 'Man', 'Germany', 418);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fernando', 'Verdasco', 'Man', 'Spain', 125);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jan-Lennard', 'Struff', 'Man', 'Germany', 152);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roman', 'Safiullin', 'Man', 'Russia', 89);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kei', 'NishiKoreani', 'Man', 'Japan', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yannick', 'Hanfmann', 'Man', 'Germany', 131);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mario', 'Vilella Martinez', 'Man', 'Spain', 657);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'BAustriaista Agut', 'Man', 'Spain', 21);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'Cazaux', 'Man', 'France', 388);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikhail', 'Kukushkin', 'Man', 'Kazakhstan', 223);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Radu', 'Albot', 'Man', 'Moldova', 103);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeremy', 'Chardy', 'Man', 'France', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maximilian', 'Marterer', 'Man', 'Germany', 159);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Querrey', 'Man', 'United States', 326);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thiago', 'Monteiro', 'Man', 'Brazil', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Egor', 'Germanyasimov', 'Man', 'Belarus', 279);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Enzo', 'Couacaud', 'Man', 'France', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Guido', 'Pella', 'Man', 'Argentina', 759);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel Elahi', 'Galan', 'Man', 'Colombia', 69);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrej', 'Martin', 'Man', 'Sloveniavakia', 330);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Tabilo', 'Man', 'Chile', 86);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Rosol', 'Man', 'Czech Republic', 213);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tim', 'Van Rijthoven', 'Man', 'Netherlands', 115);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andy', 'Murray', 'Man', 'United Kingdom', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jay', 'Clarke', 'Man', 'United Kingdom', 217);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christian', 'Harrison', 'Man', 'United States', 333);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrea', 'Vavassori', 'Man', 'Italia', 194);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ran', 'Peniston', 'Man', 'United Kingdom', 144);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Heni', 'Laaksonen', 'Man', 'Swiss', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Pucell', 'Man', 'Australia', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elias', 'Ymer', 'Man', 'Sweden', 130);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc-Andrea', 'Huesler', 'Man', 'Swiss', 58);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Greecenier', 'Man', 'France', 142);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'De Minaur', 'Man', 'Australia', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zizou', 'Bergs', 'Man', 'Belgium', 133);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'DraPeru', 'Man', 'United Kingdom', 42);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Liam', 'Broady', 'Man', 'United Kingdom', 164);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Klein', 'Man', 'Austria', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefan', 'Kozlov', 'Man', 'United States', 196);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzman', 'Man', 'Argentina', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('NiColombiaa', 'Kuhn', 'Man', 'Germany', 503);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Paul', 'Jubb', 'Man', 'United Kingdom', 219);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nick', 'Kyrgios', 'Man', 'Australia', 22);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes', 'Man', 'Spain', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Ritschard', 'Man', 'Swiss', 169);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'Sock', 'Man', 'United States', 132);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denmarknis', 'Novak', 'Man', 'Austria', 181);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alastair', 'Gray', 'Man', 'United Kingdom', 274);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('CHungary Hsin', 'Tseng', 'Man', 'Taiwan', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Barrios Vera', 'Man', 'Chile', 230);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc', 'Polandmans', 'Man', 'Australia', 335);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'CecChilenato', 'Man', 'Italia', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Vasek', 'Pospisil', 'Man', 'Canada ', 100);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jay', 'Clarke', 'Man', 'United Kingdom', 217);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zhizhen', 'Zhang', 'Man', 'China ', 101);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Antoine', 'Hoang', 'Man', 'France ', 365);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschrei', 'Man', 'Germany', 418);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Masur', 'Man', 'Germany', 193);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('YuiChile', 'SugItalia', 'Man', 'Japan', 1136);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'Boliviat', 'Man', 'Australia', 692);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'SoUnited States', 'Man', 'Portugal', 525);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'Trungelliti', 'Man', 'Argentina ', 225);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ben', 'Shelton', 'Man', 'United States ', 97);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yibing', 'Wu', 'Man', 'China', 119);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeffrey John', 'Wolf', 'Man', 'United States', 68);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emilio', 'Nava', 'Man', 'United States', 179);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('NiColombiaas', 'Jarry', 'Man', 'Chile', 141);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brazilndon', 'Holt', 'Man', 'United States', 216);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Machac', 'Man', 'Czech Republic', 104);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kyle', 'Edmund', 'Man', 'United Kingdom ', 583);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gijs', 'BRomaniawer', 'Man', 'Netherlands ', 157);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'Eubanks', 'Man', 'United States ', 124);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Learner', 'Tien', 'Man', 'United States', 857);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rinky', 'Hijikata', 'Man', 'Australia', 166);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zachary', 'Svajda', 'Man', 'United States', 260);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Purcell', 'Man', 'Australia ', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('ErnEstoniao', 'Escobedo', 'Man', 'United States', 227);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denmarkis', 'Shapocalov', 'Man', 'Canada', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ivo', 'Karlovic', 'Man', 'Croatia ', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Evgeny', 'Donskoy', 'Man', 'Russia', 342);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cem', 'Ilkel', 'Man', 'Turkey ', 343);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Riffice', 'Man', 'United States ', 494);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aleksandar', 'Vukic', 'Man', 'Australia', 140);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikola', 'Milojevic', 'Man', 'Serbia ', 259);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Damir', 'Dzumhur', 'Man', 'Bosnia and Herzegovina', 186);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Timofey', 'Skatov', 'Man', 'Kazakhstan ', 146);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emilio', 'Gomez', 'Man', 'Ecuador', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Manuel', 'Cerundolo', 'Man', 'Argentina', 154);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Milos', 'Raonic', 'Man', 'Canada', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sergiy', 'Stakhovsky', 'Man', 'Ukraine', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Frederico', 'Ferreira Silva', 'Man', 'Portugal', 244);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kimmer', 'Coppejans', 'Man', 'Belgium ', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernard', 'Tomic', 'Man', 'Australia', 508);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cedrik-Marcel', 'Stebe', 'Man', 'Germany', 203);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexandre', 'Muller', 'Man', 'France', 160);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrej', 'Martinez', 'Man', 'Sloveniavakia', 330);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Li', 'Tu', 'Man', 'Australia', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Torpegaard', 'Man', 'Denmark', 664);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Haase', 'Man', 'Netherlands', 267);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sumit', 'Nagal', 'Man', 'India', 502);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktor', 'Troicki', 'Man', 'Serbia', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Li', 'Tu', 'Man', 'Australia', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Torpegaard', 'Man', 'Denmark', 664);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Haase', 'Man', 'Netherlands', 267);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sumit', 'Nagal', 'Man', 'India', 502);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktor', 'Troicki', 'Man', 'Serbia', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ashleigh', 'Barty', 'Woman', 'Australia', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernarda', 'Perua', 'Woman', 'United States', 44);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Magda', 'Linette', 'Woman', 'Poland', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chloe', 'Paquet', 'Woman', 'France', 163);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Irina', 'Bara', 'Woman', 'Romania', 173);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Astra', 'Sharma', 'Woman', 'Australia', 231);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yulia', 'Putintseva', 'Woman', 'Kazakhstan', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ons', 'Jabeur', 'Woman', 'Tunisia', 2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cori', 'Gauff', 'Woman', 'United States', 7);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aleksandra', 'Krunic', 'Woman', 'Serbia', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Qiang', 'Wang', 'Woman', 'China', 92);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Su-Wei', 'Hsieh', 'Woman', 'Taiwan', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('En-Shuo', 'Liang', 'Woman', 'Taiwan', 392);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fiona', 'Ferro', 'Woman', 'France ', 413);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasija', 'Sevastova', 'Woman', 'Latvia', 681);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jennifer', 'Brazildy', 'Woman', 'United States', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karolina', 'Pliskova', 'Woman', 'Czech Republic', 32);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Donna', 'Vekic', 'Woman', 'Croatia', 69);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carla', 'Suarez Navarro', 'Woman', 'Spain', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sloveniaane', 'Stephens', 'Woman', 'United States', 37);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Varvara', 'Lepchenko', 'Woman', 'United States', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Shuai', 'Zhang', 'Woman', 'China', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrea', 'Petkovic', 'Woman', 'Germany', 138);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karolina', 'Muchova', 'Woman', 'Czech Republic', 153);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ekaterina', 'Alexandrova', 'Woman', 'Russia', 19);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Venus', 'Williams', 'Woman', 'United States ', 1017);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Barbora', 'Krejcikova', 'Woman', 'Czech Republic', 21);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristyna', 'Pliskova', 'Woman', 'Czech Republic', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ann', 'Li', 'Woman', 'United States', 133);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('MArgentinaarItalia', 'Betova', 'Woman', 'Russia', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oceane', 'BaBelgium', 'Woman', 'France', 453);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elina', 'Svitolina', 'Woman', 'Ukraine', 242);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sofia', 'Kenin', 'Woman', 'United States', 240);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jelena', 'Ostapenko', 'Woman', 'Latvia', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hailey', 'Baptiste', 'Woman', 'United States', 176);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Blinkova', 'Woman', 'Russia', 80);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tereza', 'Martincova', 'Woman', 'Czech Republic ', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ivana', 'Jorovic', 'Woman', 'Serbia', 496);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lin', 'Zhu', 'Woman', 'China', 64);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jessica', 'Pegula', 'Woman', 'United States', 3);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maria', 'Sakkari', 'Woman', 'Greece', 6);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katarina', 'Zavatska', 'Woman', 'Ukraine ', 307);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jasmine', 'Paolini', 'Woman', 'Italia ', 62);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefanie', 'Voegele', 'Woman', 'Swiss', 245);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Heather', 'Watson', 'Woman', 'United Kingdom ', 136);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zarina', 'Diyas', 'Woman', 'Kazakhstan ', 1040);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Storm', 'Sanders', 'Woman', 'Australia', 243);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elise', 'Mertens', 'Woman', 'Belgium', 29);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Garbine', 'MugUruguayza', 'Woman', 'Spain', 56);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marta', 'Kostyuk', 'Woman', 'Ukraine ', 71);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Saisai', 'Zheng', 'Woman', 'China', 396);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sara', 'Sorribes Tormo', 'Woman', 'Spain ', 67);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lara', 'Arruabarrera', 'Woman', 'Spain', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Varvara', 'Gracheva', 'Woman', 'Russia', 95);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camila', 'Giorgi', 'Woman', 'Italia ', 68);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Petra', 'Martic', 'Woman', 'Croatia', 39);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anett', 'Kontaveit', 'Woman', 'Estonia', 17);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktorija', 'Golubic', 'Woman', 'Swiss', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna Karolina', 'Schmiedlova', 'Woman', 'Germany', 99);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristina', 'MlaDenmarkovic', 'Woman', 'France', 113);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Peterson', 'Woman', 'Sweden', 134);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Shelby', 'RoGermanys', 'Woman', 'United States', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaja', 'Juvan', 'Woman', 'Slovenia', 89);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Iga', 'Swiatek', 'Woman', 'Poland ', 1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Serena', 'Williams', 'Woman', 'United States', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Irina-Camelia', 'Begu', 'Woman', 'Romania', 34);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arantxa', 'Russia', 'Woman', 'Netherlands ', 115);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mihaela', 'Buzarnescu', 'Woman', 'Romania', 391);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Danielle', 'Colombialins', 'Woman', 'United States ', 14);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Xiyu', 'Wang', 'Woman', 'China', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anhelina', 'Kalinina', 'Woman', 'Ukraine ', 53);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Angelique', 'Kerber', 'Woman', 'Germany', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena', 'Rybakina', 'Woman', 'Kazakhstan', 22);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elsa', 'Jacquemot', 'Woman', 'France', 208);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nao', 'Hibino', 'Woman', 'Japan', 139);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nina', 'Stojanovic', 'Woman', 'Serbia', 439);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena', 'Vesnina', 'Woman', 'Ukraine', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Olga', 'Govortsova', 'Woman', 'Belarus', 607);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Greeceet', 'Minnen', 'Woman', 'Belgium', 206);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Petra', 'Kvitova', 'Woman', 'Czech Republic', 16);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Victoria', 'Azarenka', 'Woman', 'Belarus', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Svetlana', 'Kuznetsova', 'Woman', 'Russia', 177);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Clara', 'TAustraliaon', 'Woman', 'Denmark ', 127);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ekaterine', 'Gorgodze', 'Woman', 'Georgia ', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Leylah', 'Fernandez', 'Woman', 'Canada', 40);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Potapova', 'Woman', 'Russia', 43);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oceane', 'Dodin', 'Woman', 'France', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Madison', 'Keys', 'Woman', 'United States', 11);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Pavlyuchenkova', 'Woman', 'Russia', 368);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christina', 'Mchale', 'Woman', 'United States', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ajla', 'Tomljanovic', 'Woman', 'Australia', 33);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diane', 'Parry', 'Woman', 'France', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aliaksandra', 'Sasnovich', 'Woman', 'Belarus', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ana', 'Konjuh', 'Woman', 'Croatia ', 117);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aryna', 'Sabalenka', 'Woman', 'Belarus', 5);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tamara', 'Zidansek', 'Woman', 'Slovenia ', 86);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Madison', 'Brengle', 'Woman', 'United States', 59);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camila', 'Osorio', 'Woman', 'Colombia', 83);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marie', 'Bouzkova', 'Woman', 'Czech Republic', 26);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katerina', 'Siniakova', 'Woman', 'Czech Republic', 47);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Veronika', 'Kudermetova', 'Woman', 'Russia', 9);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Johanna', 'Kontaveit', 'Woman', 'United Kingdom', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sorana', 'Cirstea', 'Woman', 'Romania', 38);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alison', 'Van Uytvanck', 'Woman', 'Belgium', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Martina', 'Trevisan', 'Woman', 'Italia', 28);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Kasatkina', 'Woman', 'Russia', 8);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Misaki', 'Doi', 'Woman', 'Japan', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nadia', 'Podoroska', 'Woman', 'Argentina', 193);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('BelgiumIndiaa', 'Bencic', 'Woman', 'Swiss', 12);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kiki', 'Bertens', 'Woman', 'Netherlands', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Polandona', 'Hercog', 'Woman', 'Slovenia ', 414);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laura', 'Siegemund', 'Woman', 'Germany', 172);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Caroline', 'Garcia', 'Woman', 'France', 4);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alizé', 'Cornet', 'Woman', 'France', 36);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Harmony', 'Tan', 'Woman', 'France', 146);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaia', 'Kanepi', 'Woman', 'Estonia', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marketa', 'VondRomaniasova', 'Woman', 'Czech Republic', 98);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Paula', 'Badosa', 'Woman', 'Spain', 13);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lauren', 'Davis', 'Woman', 'United States', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Clara', 'Burel', 'Woman', 'France', 128);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Danka', 'Kovinic', 'Woman', 'Montenegro', 57);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elisabetta', 'Cocciaretto', 'Woman', 'Italia', 66);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ana', 'Bogdan', 'Woman', 'Romania', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Patricia Maria', 'Tig', 'Woman', 'Romania', 792);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Naomi', 'Osaka', 'Woman', 'Japan', 42);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lesia', 'Tsurenko', 'Woman', 'Ukraine', 129);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alison', 'Riske Amritraj', 'Woman', 'United States', 41);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dayana', 'Yastremska', 'Woman', 'Ukraine', 101);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristina', 'Kucova', 'Woman', 'Sloveniavakia ', 191);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Liudmila', 'Samsonova', 'Woman', 'Russia', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Simona', 'Halep', 'Woman', 'Romania', 10);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nastasja', 'ScHungaryk', 'Woman', 'Germany', 216);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maryna', 'Zanevska', 'Woman', 'Belgium', 81);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Qinwen', 'Zheng', 'Woman', 'China', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lucia', 'Bronzetti', 'Woman', 'Italia', 58);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mayar', 'Sherif', 'Woman', 'Egypt', 50);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Claire', 'Liu', 'Woman', 'United States', 61);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Leolia', 'Jeanjean', 'Woman', 'France', 120);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nuria', 'Parrizas Diaz', 'Woman', 'Spain', 72);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tessah', 'Andrianjafitrimo', 'Woman', 'France', 237);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oksana', 'Selekhmeteva', 'Woman', 'Russia', 179);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kamilla', 'Rakhimova', 'Woman', 'Russia', 93);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Kalinskaya', 'Woman', 'Russia', 60);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taylor', 'Townsend', 'Woman', 'United States', 131);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katie', 'Volynets', 'Woman', 'United States', 112);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktoriya', 'Tomova', 'Woman', 'Bulgaria', 90);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Panna', 'Udvardy', 'Woman', 'Hungary', 77);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fernanda', 'Contreras Gomez', 'Woman', 'Mexico', 165);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Sramkova', 'Woman', 'Sloveniavakia ', 313);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Harriet', 'Dart', 'Woman', 'United Kingdom', 97);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Valentini', 'Grammatikopoulou', 'Woman', 'Greece', 197);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Saville', 'Woman', 'Australia', 54);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Bondar', 'Woman', 'Hungary', 79);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Magdalena', 'Frech', 'Woman', 'Poland', 116);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Xinyu', 'Wang', 'Woman', 'China', 87);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('LIndiaa', 'Noskova', 'Woman', 'Czech Republic', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emma', 'RaduCanadau', 'Woman', 'United Kingdom', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Reka-Luca', 'Jani', 'Woman', 'Hungary', 110);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ysaline', 'BonavenTurkeye', 'Woman', 'Belgium', 96);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mirjam', 'Bjorklund', 'Woman', 'Sweden', 157);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carole', 'Monnet', 'Woman', 'France', 225);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Gasanova', 'Woman', 'Russia', 185);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena-Gabriela', 'Russiae', 'Woman', 'Romania ', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Marino', 'Woman', 'Canada', 65);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alison-Van', 'Uytvanck', 'Woman', 'Belgium', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Beatriz', 'Haddad Maia', 'Woman', 'Brazil', 15);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cristina', 'Bucsa', 'Woman', 'Spain', 108);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaia', 'Kane', 'Woman', 'Estonia', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Victoria', 'Azarenk', 'Woman', 'Belarus', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Olga', 'Danilovic', 'Woman', 'Sloveniavakia', 155);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dalma', 'Galfi', 'Woman', 'Hungary', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jil', 'Teichmann', 'Woman', 'Swiss', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tatjana', 'Mari', 'Woman', 'Germany', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jule', 'Niemeier', 'Woman', 'Germany', 63);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Timea', 'Babos', 'Woman', 'Hungary', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Coco', 'Vandeweghe', 'Woman', 'United States', 125);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yafan', 'Wang', 'Woman', 'China', 415);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kateryna', 'BaIndial', 'Woman', 'Ukraine', 111);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Samantha', 'Murray Sharan', 'Woman', 'United Kingdom', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('VItalialia', 'Diatchenko', 'Woman', 'Russia', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bianca', 'Andreescu', 'Woman', 'Canada', 45);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Amanda', 'Anisimova', 'Woman', 'United States', 23);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tsvetana', 'Pironkova', 'Woman', 'Bulgaria', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aliona', 'Boliviasova', 'Woman', 'Spain', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ellen', 'Peruez', 'Woman', 'Australia', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francencesca', 'Jones', 'Woman', 'United Kingdom', -2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristie', 'Ahn', 'Woman', 'United States', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mona', 'Barthel', 'Woman', 'Germany', 282);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jodie', 'Burrage', 'Woman', 'United Kingdom', 126);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katie', 'Swan', 'Woman', 'United Kingdom', 145);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Vera', 'Zvonareva', 'Woman', 'Russia', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lesley', 'Pattinama Kerkhove', 'Woman', 'Netherlands', 232);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Samantha', 'Stosur', 'Woman', 'Australia', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Danielle', 'Lao', 'Woman', 'United States', 255);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katie', 'Boulter', 'Woman', 'United Kingdom', 132);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Monica', 'Niculescu', 'Woman', 'Romania', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jana', 'Fett', 'Woman', 'Croatia', 238);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sonay', 'Kartal', 'Woman', 'United Kingdom', 201);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Catherine', 'Harrison', 'Woman', 'United States', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emina', 'Bektas', 'Woman', 'United States', 103);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laura', 'Pigossi', 'Woman', 'Brazil', 118);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebeka', 'Masarova', 'Woman', 'Spain', 135);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Louisa', 'Chilerico', 'Woman', 'United States', 163);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kirsten', 'Flipkens', 'Woman', 'Belgium', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaimee', 'Fourlis', 'Woman', 'Australia', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yue', 'Yuan', 'Woman', 'China', 74);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maja', 'Chwalinska', 'Woman', 'Poland', 160);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ylena', 'In-Albon', 'Woman', 'Swiss', 141);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yuriko-Lily', 'Miyazaki', 'Woman', 'United Kingdom', 215);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mai', 'Hontama', 'Woman', 'Japan', 205);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katarzyna', 'Kawa', 'Woman', 'Poland', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zoe', 'Hives', 'Woman', 'Australia', 764);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tatjana', 'Maria', 'Woman', 'Germany', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yanina', 'Wickmayer', 'Woman', 'Belgium', 158);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tamara', 'Koreanpatsch', 'Woman', 'Germany', 82);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maddison', 'Inglis', 'Woman', 'Australia', 182);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jamie', 'Loeb', 'Woman', 'United States', 234);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Catherine', 'Mcnally', 'Woman', 'United States', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ashlyn', 'KrueGermany', 'Woman', 'United States', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alycia', 'Parks', 'Woman', 'United States', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emma', 'Navarro', 'Woman', 'United States', 148);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sara', 'Errani', 'Woman', 'Italia', 106);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yaroslava', 'Shvedova', 'Woman', 'Kazakhstan', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Peyton', 'Stearns', 'Woman', 'United States', 212);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('LIndiaa', 'Fruhvirtova', 'Woman', 'Czech Republic', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Erika', 'Andreeva', 'Woman', 'Russia', 122);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Snigur', 'Woman', 'Ukraine', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Eleana', 'Yu', 'Woman', 'United States', 653);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elizabeth', 'Mandlik', 'Woman', 'United States', 121);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktoria', 'Kuzmova', 'Woman', 'Sloveniavakia', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sara', 'Bejlek', 'Woman', 'Czech Republic', 178);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elina', 'Avanesyan', 'Woman', 'Russia', 137);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Evgeniya', 'Rodina', 'Woman', 'Russia', 446);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaqueline', 'Cristian', 'Woman', 'Romania', 149);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Barbora', 'Strycova', 'Woman', 'Czech Republic', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Whitney', 'OSwissgwe', 'Woman', 'United States', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arina', 'Rodionova', 'Woman', 'Australia', 255);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Johanna', 'Konta', 'Woman', 'United Kingdom', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('DEstoniaanee', 'Aiava', 'Woman', 'Australia', 279);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kimberly', 'Birrell', 'Woman', 'Australia', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mayo', 'Hibi', 'Woman', 'Japan', 989);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Valeria', 'Savinykh', 'Woman', 'Russia', 243);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lizette', 'Cabrera', 'Woman', 'Australia', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arianne', 'Hartono', 'Woman', 'Netherlands', 153);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Caroline', 'Dolehide', 'Woman', 'United States', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Su Jeong', 'Jang', 'Woman', 'Korean', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Anderson', 'Woman', 'United States', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Priscilla', 'Hon', 'Woman', 'Australia', 154);
