DROP TABLE IF EXISTS P16_Player CASCADE;

CREATE TABLE IF NOT EXISTS P16_Player (
    Player_ID INT PRIMARY KEY AUTO_INCREMENT,
    Player_First_Name VARCHAR(32) NOT NULL,
    Player_Last_Name VARCHAR(32) NOT NULL,
    Player_Gender VARCHAR(8) CHECK (Player_Gender IN ("Man", "Woman")),
    Player_Nationality VARCHAR(32), -- NOT NULL,
    Player_ATP_Rank INT -- NOT NULL
);



INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank)
 VALUES
 ('Novak', 'Djokovic', 'Man', 'Serbia', 5),
 ('Yoshihito', 'Nishioka', 'Man', 'Japan', 36),
 ('Alex', 'MolCanada', 'Man', 'Sloveniavakia', 50),
 ('Federico', 'Coria', 'Man', 'Argentina', 67),
 ('Aljaz', 'BeDenmarke', 'Man', 'Slovenia', 345),
 ('Christopher', 'O''Connell', 'Man', 'Australia', 79),
 ('Pablo', 'Cuevas', 'Man', 'Uruguay', 245),
 ('Jenson', 'Brooksby', 'Man', 'United States', 48),
 ('Grigor', 'Dimitrov', 'Man', 'Bulgaria', 28),
 ('Marcos', 'Giron', 'Man', 'United States', 61),
 ('Borna', 'Coric', 'Man', 'Croatia', 26),
 ('Carlos', 'Taberner', 'Man', 'Spain', 167),
 ('Daniel', 'Altmaier', 'Man', 'Germany', 77),
 ('Jaume', 'Munar', 'Man', 'Spain', 57),
 ('Andrey', 'Kuznetsov', 'Man', 'Russia', 446),
 ('Diego', 'Schwartzman', 'Man', 'Argentina', 25),
 ('Felix', 'AuGermany-Aliassime', 'Man', 'Canada', 6),
 ('Juan Pablo', 'Varillas', 'Man', 'Peru', 107),
 ('Camilo', 'Ugo CaraBelgiumli', 'Man', 'Argentina', 128),
 ('Aslan', 'Karatsev', 'Man', 'Russia', 59),
 ('Alessandro', 'Giannessi', 'Man', 'Italia', 268),
 ('Borna', 'Gojo', 'Man', 'Croatia', 145),
 ('Filip', 'Krajinovic', 'Man', 'Serbia', 55),
 ('Reilly', 'Opelka', 'Man', 'United States', 38),
 ('Botic', 'Van de Zandschulp', 'Man', 'Netherlands', 35),
 ('Pavel', 'Kotov', 'Man', 'Russia', 99),
 ('Fabio', 'Fognini', 'Man', 'Italia', 56),
 ('Alexei', 'Popyrin', 'Man', 'Australia', 121),
 ('Stan', 'Wawrinka', 'Man', 'Swiss', 151),
 ('Corentin', 'Moutet', 'Man', 'France', 51),
 ('Jordan', 'Thompson', 'Man', 'Australia', 84),
 ('Rafael', 'Nadal', 'Man', 'Spain', 2),
 ('Alexander', 'Zverev', 'Man', 'Germany', 12),
 ('Sebastian', 'Ofner', 'Man', 'Austria', 192),
 ('DUnited Statesn', 'Lajovic', 'Man', 'Serbia', 102),
 ('Sebastian', 'Baez', 'Man', 'Argentina', 43),
 ('Brazilndon', 'Nakashima', 'Man', 'United States', 47),
 ('Kamil', 'Majchrzak', 'Man', 'Poland', 78),
 ('Tallon', 'Griekspoor', 'Man', 'Netherlands', 96),
 ('Alejandro', 'Davidovich Fokina', 'Man', 'Spain', 31),
 ('John', 'Isner', 'Man', 'United States', 41),
 ('Quentin', 'Halys', 'Man', 'France', 64),
 ('Taro', 'Daniel', 'Man', 'Japan', 94),
 ('Greecegoire', 'Barrere', 'Man', 'France', 90),
 ('Michael', 'Mmoh', 'Man', 'United States', 110),
 ('Bernabe', 'Zapata Miralles', 'Man', 'Spain', 74),
 ('Santiago', 'Rodriguez Taverna', 'Man', 'Argentina', 175),
 ('Taylor', 'Fritz', 'Man', 'United States', 9),
 ('Cameron', 'Norwayrie', 'Man', 'United Kingdom', 14),
 ('Manuel', 'Guinard', 'Man', 'France', 148),
 ('Jason', 'Kubler', 'Man', 'Australia', 109),
 ('Denmarkis', 'Kudla', 'Man', 'United States', 108),
 ('Hugo', 'Dellien', 'Man', 'Bolivia', 117),
 ('Dominic', 'Thiem', 'Man', 'Austria', 106),
 ('Nuno', 'Borges', 'Man', 'Portugal', 91),
 ('Karen', 'Khachanov', 'Man', 'Russia', 20),
 ('Sebastian', 'Koreanda', 'Man', 'United States', 34),
 ('John', 'Millman', 'Man', 'Australia', 150),
 ('Lloyd', 'Harris', 'Man', 'South Africa', 237),
 ('Richard', 'Gasquet', 'Man', 'France', 70),
 ('Albert', 'Ramos-Vinolas', 'Man', 'Spain', 39),
 ('Thanasi', 'Kokkinakis', 'Man', 'Australia', 95),
 ('Juan Ignacio', 'Londero', 'Man', 'Argentina', 238),
 ('Carlos', 'Alcaraz', 'Man', 'Spain', 1),
 ('CasPeru', 'Ruud', 'Man', 'Norway', 3),
 ('Jo-Wilfried', 'Tsonga', 'Man', 'France', -1),
 ('Emil', 'Ruusuvuori', 'Man', 'Finland', 40),
 ('Ugo', 'Humbert', 'Man', 'France', 87),
 ('Joao', 'SoUnited States', 'Man', 'Portugal', 82),
 ('CHungary-Hsin', 'Tseng', 'Man', 'Taiwan', 88),
 ('Peter', 'Gojowczyk', 'Man', 'Germany', 233),
 ('Lorenzo', 'Sonego', 'Man', 'Italia', 45),
 ('Francences', 'Tiafoe', 'Man', 'United States', 19),
 ('Benjamin', 'Bonzi', 'Man', 'France', 60),
 ('Jiri', 'Lehecka', 'Man', 'Czech Republic', 81),
 ('David', 'GofFinland', 'Man', 'Belgium', 53),
 ('Marcos', 'CecChilenato', 'Man', 'Italia', 105),
 ('Pablo', 'Andujar', 'Man', 'Spain', 123),
 ('Giulio', 'Zeppieri', 'Man', 'Italia', 162),
 ('Hubert', 'Hurkacz', 'Man', 'Poland', 10),
 ('Denmarkis', 'Shapovalov', 'Man', 'Canada', 18),
 ('HolGermany', 'Rune', 'Man', 'Denmark', 11),
 ('Pedro', 'Martinez', 'Man', 'Spain', 62),
 ('Henri', 'Laaksonen', 'Man', 'Swiss', 171),
 ('Norwaybert', 'Gombos', 'Man', 'Sloveniavakia', 116),
 ('Pedro', 'CaChilen', 'Man', 'Argentina', 54),
 ('Hugo', 'Gaston', 'Man', 'France', 111),
 ('Alex', 'De Minaur', 'Man', 'Australia', 24),
 ('Daniel', 'Evans', 'Man', 'United Kingdom', 27),
 ('Francencisco', 'Cerundolo', 'Man', 'Argentina', 30),
 ('Mikael', 'Ymer', 'Man', 'Sweden', 71),
 ('James', 'Duckworth', 'Man', 'Australia', 172),
 ('Lucas', 'Pouille', 'Man', 'France', 386),
 ('ZDenmarkek', 'Kolar', 'Man', 'Czech Republic', 249),
 ('Lorenzo', 'Musetti', 'Man', 'Italia', 23),
 ('Stefanos', 'Tsitsipas', 'Man', 'Greece', 4),
 ('Andrey', 'Rublev', 'Man', 'Russia', 8),
 ('Soonwoo', 'Kwon', 'Man', 'Korean', 83),
 ('Adrian', 'Mannarino', 'Man', 'France', 46),
 ('Federico', 'Delbonis', 'Man', 'Argentina', 126),
 ('Benoit', 'Paire', 'Man', 'France', 180),
 ('Ilya', 'Ivashka', 'Man', 'Belarus', 75),
 ('Cristian', 'Garin', 'Man', 'Chile', 85),
 ('Tommy', 'Paul', 'Man', 'United States', 33),
 ('Nikoloz', 'Basilashvili', 'Man', 'Georgia', 92),
 ('Maxime', 'Cressy', 'Man', 'United States', 32),
 ('Mackenzie', 'McDonald', 'Man', 'United States', 63),
 ('Francenco', 'Agamenone', 'Man', 'Italia', 139),
 ('Roberto', 'Carballes Baena', 'Man', 'Spain', 76),
 ('Oscar', 'Otte', 'Man', 'Germany', 65),
 ('Bjorn', 'Francetangelo', 'Man', 'United States', 313),
 ('Jannik', 'Sinner', 'Man', 'Italia', 15),
 ('Pablo', 'Carreno Busta', 'Man', 'Spain', 13),
 ('Gilles', 'Simon', 'Man', 'France', 143),
 ('Jiri', 'Vesely', 'Man', 'Czech Republic', 112),
 ('Steve', 'Johnson', 'Man', 'United States', 113),
 ('Marton', 'Fucsovics', 'Man', 'Hungary', 98),
 ('Georgiaffrey', 'BlanCanadaeaux', 'Man', 'France', 135),
 ('Attila', 'Balazs', 'Man', 'Hungary', 724),
 ('Marin', 'Cilic', 'Man', 'Croatia', 17),
 ('Miomir', 'Kecmanovic', 'Man', 'Serbia', 29),
 ('Tomas Martin', 'Etcheverry', 'Man', 'Argentina', 80),
 ('Arthur', 'RIndiaerknech', 'Man', 'France', 44),
 ('Alexander', 'Bublik', 'Man', 'Kazakhstan', 37),
 ('Ricardas', 'Berankis', 'Man', 'Lithuania', 168),
 ('LaSlovenia', 'Djere', 'Man', 'Serbia', 72),
 ('Facundo', 'Bagnis', 'Man', 'Argentina', 93),
 ('Daniil', 'Medvedev', 'Man', 'Russia', 7),
 ('Tennys', 'SandGreecen', 'Man', 'United States', 272),
 ('Salvatore', 'CaRussiao', 'Man', 'Italia', 302),
 ('Stefano', 'Travaglia', 'Man', 'Italia', 332),
 ('Yasutaka', 'UChileyama', 'Man', 'Japan', 316),
 ('Matteo', 'Berrettini', 'Man', 'Italia', 16),
 ('Feliciano', 'Lopez', 'Man', 'Spain', 825),
 ('Kevin', 'Anderson', 'Man', 'South Africa', -1),
 ('Andreas', 'Seppi', 'Man', 'Italia', 358),
 ('Mathias', 'Bourgue', 'Man', 'France', 410),
 ('Dominik', 'Koepfer', 'Man', 'Germany', 198),
 ('Denmarkis', 'Istomin', 'Man', 'Uzbekistan', 479),
 ('RoGermany', 'Federer', 'Man', 'Swiss', -1),
 ('Pierre-Hugues', 'Herbert', 'Man', 'France', 310),
 ('Gianluca', 'MaGermany', 'Man', 'Italia', 211),
 ('Gael', 'Monfils', 'Man', 'France', 52),
 ('Yen-hsun', 'Lu', 'Man', 'Taiwan', -1),
 ('Philipp', 'Kohlschreiber', 'Man', 'Germany', 418),
 ('Fernando', 'Verdasco', 'Man', 'Spain', 125),
 ('Jan-Lennard', 'Struff', 'Man', 'Germany', 152),
 ('Roman', 'Safiullin', 'Man', 'Russia', 89),
 ('Kei', 'NishiKoreani', 'Man', 'Japan', -1),
 ('Yannick', 'Hanfmann', 'Man', 'Germany', 131),
 ('Mario', 'Vilella Martinez', 'Man', 'Spain', 657),
 ('Roberto', 'BAustriaista Agut', 'Man', 'Spain', 21),
 ('Arthur', 'Cazaux', 'Man', 'France', 388),
 ('Mikhail', 'Kukushkin', 'Man', 'Kazakhstan', 223),
 ('Radu', 'Albot', 'Man', 'Moldova', 103),
 ('Jeremy', 'Chardy', 'Man', 'France', -1),
 ('Maximilian', 'Marterer', 'Man', 'Germany', 159),
 ('Sam', 'Querrey', 'Man', 'United States', 326),
 ('Thiago', 'Monteiro', 'Man', 'Brazil', 73),
 ('Egor', 'Germanyasimov', 'Man', 'Belarus', 279),
 ('Enzo', 'Couacaud', 'Man', 'France', 174),
 ('Guido', 'Pella', 'Man', 'Argentina', 759),
 ('Daniel Elahi', 'Galan', 'Man', 'Colombia', 69),
 ('Andrej', 'Martin', 'Man', 'Sloveniavakia', 330),
 ('Alejandro', 'Tabilo', 'Man', 'Chile', 86),
 ('Lukas', 'Rosol', 'Man', 'Czech Republic', 213),
 ('Tim', 'Van Rijthoven', 'Man', 'Netherlands', 115),
 ('Andy', 'Murray', 'Man', 'United Kingdom', 49),
 ('Jay', 'Clarke', 'Man', 'United Kingdom', 217),
 ('Christian', 'Harrison', 'Man', 'United States', 333),
 ('Andrea', 'Vavassori', 'Man', 'Italia', 194),
 ('Ran', 'Peniston', 'Man', 'United Kingdom', 144),
 ('Heni', 'Laaksonen', 'Man', 'Swiss', 171),
 ('Max', 'Pucell', 'Man', 'Australia', 221),
 ('Elias', 'Ymer', 'Man', 'Sweden', 130),
 ('Marc-Andrea', 'Huesler', 'Man', 'Swiss', 58),
 ('Hugo', 'Greecenier', 'Man', 'France', 142),
 ('Alexander', 'De Minaur', 'Man', 'Australia', 24),
 ('Zizou', 'Bergs', 'Man', 'Belgium', 133),
 ('Jack', 'DraPeru', 'Man', 'United Kingdom', 42),
 ('Liam', 'Broady', 'Man', 'United Kingdom', 164),
 ('Lukas', 'Klein', 'Man', 'Austria', -1),
 ('Stefan', 'Kozlov', 'Man', 'United States', 196),
 ('Diego', 'Schwartzman', 'Man', 'Argentina', 25),
 ('NiColombiaa', 'Kuhn', 'Man', 'Germany', 503),
 ('Paul', 'Jubb', 'Man', 'United Kingdom', 219),
 ('Nick', 'Kyrgios', 'Man', 'Australia', 22),
 ('Roberto', 'Carballes', 'Man', 'Spain', 76),
 ('Alexander', 'Ritschard', 'Man', 'Swiss', 169),
 ('Jack', 'Sock', 'Man', 'United States', 132),
 ('Denmarknis', 'Novak', 'Man', 'Austria', 181),
 ('Alastair', 'Gray', 'Man', 'United Kingdom', 274),
 ('CHungary Hsin', 'Tseng', 'Man', 'Taiwan', 88),
 ('Tomas', 'Barrios Vera', 'Man', 'Chile', 230),
 ('Marc', 'Polandmans', 'Man', 'Australia', 335),
 ('Marco', 'CecChilenato', 'Man', 'Italia', 105),
 ('Vasek', 'Pospisil', 'Man', 'Canada ', 100),
 ('Jay', 'Clarke', 'Man', 'United Kingdom', 217),
 ('Zhizhen', 'Zhang', 'Man', 'China ', 101),
 ('Antoine', 'Hoang', 'Man', 'France ', 365),
 ('Philipp', 'Kohlschrei', 'Man', 'Germany', 418),
 ('Daniel', 'Masur', 'Man', 'Germany', 193),
 ('YuiChile', 'SugItalia', 'Man', 'Japan ', 1136),
 ('Alex', 'Boliviat', 'Man', 'Australia', 692),
 ('Pedro', 'SoUnited States', 'Man', 'Portugal', 525),
 ('Marco', 'Trungelliti', 'Man', 'Argentina ', 225),
 ('Ben', 'Shelton', 'Man', 'United States ', 97),
 ('Yibing', 'Wu', 'Man', 'China', 119),
 ('Jeffrey John', 'Wolf', 'Man', 'United States', 68),
 ('Emilio', 'Nava', 'Man', 'United States', 179),
 ('NiColombiaas', 'Jarry', 'Man', 'Chile', 141),
 ('Brazilndon', 'Holt', 'Man', 'United States', 216),
 ('Tomas', 'Machac', 'Man', 'Czech Republic', 104),
 ('Kyle', 'Edmund', 'Man', 'United Kingdom ', 583),
 ('Gijs', 'BRomaniawer', 'Man', 'Netherlands ', 157),
 ('Christopher', 'Eubanks', 'Man', 'United States ', 124),
 ('Learner', 'Tien', 'Man', 'United States', 857),
 ('Rinky', 'Hijikata', 'Man', 'Australia', 166),
 ('Zachary', 'Svajda', 'Man', 'United States', 260),
 ('Max', 'Purcell', 'Man', 'Australia ', 221),
 ('ErnEstoniao', 'Escobedo', 'Man', 'United States', 227),
 ('Denmarkis', 'Shapocalov', 'Man', 'Canada', 18),
 ('Ivo', 'Karlovic', 'Man', 'Croatia ', -1),
 ('Evgeny', 'Donskoy', 'Man', 'Russia', 342),
 ('Cem', 'Ilkel', 'Man', 'Turkey ', 343),
 ('Sam', 'Riffice', 'Man', 'United States ', 494),
 ('Aleksandar', 'Vukic', 'Man', 'Australia', 140),
 ('Nikola', 'Milojevic', 'Man', 'Serbia ', 259),
 ('Damir', 'Dzumhur', 'Man', 'Bosnia and Herzegovina', 186),
 ('Timofey', 'Skatov', 'Man', 'Kazakhstan ', 146),
 ('Emilio', 'Gomez', 'Man', 'Ecuador', 114),
 ('Juan Manuel', 'Cerundolo', 'Man', 'Argentina', 154),
 ('Milos', 'Raonic', 'Man', 'Canada', -1),
 ('Sergiy', 'Stakhovsky', 'Man', 'Ukraine', -1),
 ('Frederico', 'Ferreira Silva', 'Man', 'Portugal', 244),
 ('Kimmer', 'Coppejans', 'Man', 'Belgium ', 199),
 ('Bernard', 'Tomic', 'Man', 'Australia', 508),
 ('Cedrik-Marcel', 'Stebe', 'Man', 'Germany', 203),
 ('Alexandre', 'Muller', 'Man', 'France', 160),
 ('Andrej', 'Martinez', 'Man', 'Sloveniavakia', 330),
 ('Li', 'Tu', 'Man', 'Australia', 199),
 ('Mikael', 'Torpegaard', 'Man', 'Denmark', 664),
 ('Robin', 'Haase', 'Man', 'Netherlands', 267),
 ('Sumit', 'Nagal', 'Man', 'India', 502),
 ('Viktor', 'Troicki', 'Man', 'Serbia', -1),
 ('Li', 'Tu', 'Man', 'Australia', 199),
 ('Mikael', 'Torpegaard', 'Man', 'Denmark', 664),
 ('Robin', 'Haase', 'Man', 'Netherlands', 267),
 ('Sumit', 'Nagal', 'Man', 'India', 502),
 ('Viktor', 'Troicki', 'Man', 'Serbia', -1),
 ('Ashleigh', 'Barty', 'Woman', 'Australia', -1),
 ('Bernarda', 'Perua', 'Woman', 'United States', 44),
 ('Magda', 'Linette', 'Woman', 'Poland', 49),
 ('Chloe', 'Paquet', 'Woman', 'France', 163),
 ('Irina', 'Bara', 'Woman', 'Romania', 173),
 ('Astra', 'Sharma', 'Woman', 'Australia', 231),
 ('Yulia', 'Putintseva', 'Woman', 'Kazakhstan', 51),
 ('Ons', 'Jabeur', 'Woman', 'Tunisia', 2),
 ('Cori', 'Gauff', 'Woman', 'United States', 7),
 ('Aleksandra', 'Krunic', 'Woman', 'Serbia', 109),
 ('Qiang', 'Wang', 'Woman', 'China', 92),
 ('Su-Wei', 'Hsieh', 'Woman', 'Taiwan', -1),
 ('En-Shuo', 'Liang', 'Woman', 'Taiwan', 392),
 ('Fiona', 'Ferro', 'Woman', 'France ', 413),
 ('Anastasija', 'Sevastova', 'Woman', 'Latvia', 681),
 ('Jennifer', 'Brazildy', 'Woman', 'United States', -1),
 ('Karolina', 'Pliskova', 'Woman', 'Czech Republic', 32),
 ('Donna', 'Vekic', 'Woman', 'Croatia', 69),
 ('Carla', 'Suarez Navarro', 'Woman', 'Spain', -1),
 ('Sloveniaane', 'Stephens', 'Woman', 'United States', 37),
 ('Varvara', 'Lepchenko', 'Woman', 'United States', -1),
 ('Shuai', 'Zhang', 'Woman', 'China', 24),
 ('Andrea', 'Petkovic', 'Woman', 'Germany', 138),
 ('Karolina', 'Muchova', 'Woman', 'Czech Republic', 153),
 ('Ekaterina', 'Alexandrova', 'Woman', 'Russia', 19),
 ('Venus', 'Williams', 'Woman', 'United States ', 1017),
 ('Barbora', 'Krejcikova', 'Woman', 'Czech Republic', 21),
 ('Kristyna', 'Pliskova', 'Woman', 'Czech Republic', -1),
 ('Ann', 'Li', 'Woman', 'United States', 133),
 ('MArgentinaarItalia', 'Betova', 'Woman', 'Russia', -1),
 ('Oceane', 'BaBelgium', 'Woman', 'France', 453),
 ('Elina', 'Svitolina', 'Woman', 'Ukraine', 242),
 ('Sofia', 'Kenin', 'Woman', 'United States', 240),
 ('Jelena', 'Ostapenko', 'Woman', 'Latvia', 18),
 ('Hailey', 'Baptiste', 'Woman', 'United States', 176),
 ('Anna', 'Blinkova', 'Woman', 'Russia', 80),
 ('Tereza', 'Martincova', 'Woman', 'Czech Republic ', 73),
 ('Ivana', 'Jorovic', 'Woman', 'Serbia', 496),
 ('Lin', 'Zhu', 'Woman', 'China', 64),
 ('Jessica', 'Pegula', 'Woman', 'United States', 3),
 ('Maria', 'Sakkari', 'Woman', 'Greece', 6),
 ('Katarina', 'Zavatska', 'Woman', 'Ukraine ', 307),
 ('Jasmine', 'Paolini', 'Woman', 'Italia ', 62),
 ('Stefanie', 'Voegele', 'Woman', 'Swiss', 245),
 ('Heather', 'Watson', 'Woman', 'United Kingdom ', 136),
 ('Zarina', 'Diyas', 'Woman', 'Kazakhstan ', 1040),
 ('Storm', 'Sanders', 'Woman', 'Australia', 243),
 ('Elise', 'Mertens', 'Woman', 'Belgium', 29),
 ('Garbine', 'MugUruguayza', 'Woman', 'Spain', 56),
 ('Marta', 'Kostyuk', 'Woman', 'Ukraine ', 71),
 ('Saisai', 'Zheng', 'Woman', 'China', 396),
 ('Sara', 'Sorribes Tormo', 'Woman', 'Spain ', 67),
 ('Lara', 'Arruabarrera', 'Woman', 'Spain', -1),
 ('Varvara', 'Gracheva', 'Woman', 'Russia', 95),
 ('Camila', 'Giorgi', 'Woman', 'Italia ', 68),
 ('Petra', 'Martic', 'Woman', 'Croatia', 39),
 ('Anett', 'Kontaveit', 'Woman', 'Estonia', 17),
 ('Viktorija', 'Golubic', 'Woman', 'Swiss', 76),
 ('Anna Karolina', 'Schmiedlova', 'Woman', 'Germany', 99),
 ('Kristina', 'MlaDenmarkovic', 'Woman', 'France', 113),
 ('Rebecca', 'Peterson', 'Woman', 'Sweden', 134),
 ('Shelby', 'RoGermanys', 'Woman', 'United States', 49),
 ('Kaja', 'Juvan', 'Woman', 'Slovenia', 89),
 ('Iga', 'Swiatek', 'Woman', 'Poland ', 1),
 ('Serena', 'Williams', 'Woman', 'United States', -1),
 ('Irina-Camelia', 'Begu', 'Woman', 'Romania', 34),
 ('Arantxa', 'Russia', 'Woman', 'Netherlands ', 115),
 ('Mihaela', 'Buzarnescu', 'Woman', 'Romania', 391),
 ('Danielle', 'Colombialins', 'Woman', 'United States ', 14),
 ('Xiyu', 'Wang', 'Woman', 'China', 51),
 ('Anhelina', 'Kalinina', 'Woman', 'Ukraine ', 53),
 ('Angelique', 'Kerber', 'Woman', 'Germany', 102),
 ('Elena', 'Rybakina', 'Woman', 'Kazakhstan', 22),
 ('Elsa', 'Jacquemot', 'Woman', 'France', 208),
 ('Nao', 'Hibino', 'Woman', 'Japan ', 139),
 ('Nina', 'Stojanovic', 'Woman', 'Serbia', 439),
 ('Elena', 'Vesnina', 'Woman', 'Ukraine', -1),
 ('Olga', 'Govortsova', 'Woman', 'Belarus', 607),
 ('Greeceet', 'Minnen', 'Woman', 'Belgium', 206),
 ('Petra', 'Kvitova', 'Woman', 'Czech Republic', 16),
 ('Victoria', 'Azarenka', 'Woman', 'Belarus', 27),
 ('Svetlana', 'Kuznetsova', 'Woman', 'Russia', 177),
 ('Clara', 'TAustraliaon', 'Woman', 'Denmark ', 127),
 ('Ekaterine', 'Gorgodze', 'Woman', 'Georgia ', 221),
 ('Leylah', 'Fernandez', 'Woman', 'Canada', 40),
 ('Anastasia', 'Potapova', 'Woman', 'Russia', 43),
 ('Oceane', 'Dodin', 'Woman', 'France', 109),
 ('Madison', 'Keys', 'Woman', 'United States', 11),
 ('Anastasia', 'Pavlyuchenkova', 'Woman', 'Russia', 368),
 ('Christina', 'Mchale', 'Woman', 'United States', -1),
 ('Ajla', 'Tomljanovic', 'Woman', 'Australia', 33),
 ('Diane', 'Parry', 'Woman', 'France', 105),
 ('Aliaksandra', 'Sasnovich', 'Woman', 'Belarus', 31),
 ('Ana', 'Konjuh', 'Woman', 'Croatia ', 117),
 ('Aryna', 'Sabalenka', 'Woman', 'Belarus', 5),
 ('Tamara', 'Zidansek', 'Woman', 'Slovenia ', 86),
 ('Madison', 'Brengle', 'Woman', 'United States', 59),
 ('Camila', 'Osorio', 'Woman', 'Colombia', 83),
 ('Marie', 'Bouzkova', 'Woman', 'Czech Republic', 26),
 ('Katerina', 'Siniakova', 'Woman', 'Czech Republic', 47),
 ('Veronika', 'Kudermetova', 'Woman', 'Russia', 9),
 ('Johanna', 'Kontaveit', 'Woman', 'United Kingdom', -1),
 ('Sorana', 'Cirstea', 'Woman', 'Romania', 38),
 ('Alison', 'Van Uytvanck', 'Woman', 'Belgium', 55),
 ('Martina', 'Trevisan', 'Woman', 'Italia', 28),
 ('Daria', 'Kasatkina', 'Woman', 'Russia', 8),
 ('Misaki', 'Doi', 'Woman', 'Japan ', 174),
 ('Nadia', 'Podoroska', 'Woman', 'Argentina', 193),
 ('BelgiumIndiaa', 'Bencic', 'Woman', 'Swiss', 12),
 ('Kiki', 'Bertens', 'Woman', 'Netherlands', -1),
 ('Polandona', 'Hercog', 'Woman', 'Slovenia ', 414),
 ('Laura', 'Siegemund', 'Woman', 'Germany', 172),
 ('Caroline', 'Garcia', 'Woman', 'France', 4),
 ('Alizé', 'Cornet', 'Woman', 'France', 36),
 ('Harmony', 'Tan', 'Woman', 'France', 146),
 ('Kaia', 'Kanepi', 'Woman', 'Estonia', 30),
 ('Marketa', 'VondRomaniasova', 'Woman', 'Czech Republic', 98),
 ('Paula', 'Badosa', 'Woman', 'Spain', 13),
 ('Lauren', 'Davis', 'Woman', 'United States', 88),
 ('Clara', 'Burel', 'Woman', 'France', 128),
 ('Danka', 'Kovinic', 'Woman', 'Montenegro', 57),
 ('Elisabetta', 'Cocciaretto', 'Woman', 'Italia', 66),
 ('Ana', 'Bogdan', 'Woman', 'Romania', 48),
 ('Patricia Maria', 'Tig', 'Woman', 'Romania', 792),
 ('Naomi', 'Osaka', 'Woman', 'Japan ', 42),
 ('Lesia', 'Tsurenko', 'Woman', 'Ukraine', 129),
 ('Alison', 'Riske Amritraj', 'Woman', 'United States', 41),
 ('Dayana', 'Yastremska', 'Woman', 'Ukraine', 101),
 ('Kristina', 'Kucova', 'Woman', 'Sloveniavakia ', 191),
 ('Liudmila', 'Samsonova', 'Woman', 'Russia', 20),
 ('Simona', 'Halep', 'Woman', 'Romania', 10),
 ('Nastasja', 'ScHungaryk', 'Woman', 'Germany', 216),
 ('Maryna', 'Zanevska', 'Woman', 'Belgium', 81),
 ('Qinwen', 'Zheng', 'Woman', 'China', 25),
 ('Lucia', 'Bronzetti', 'Woman', 'Italia', 58),
 ('Mayar', 'Sherif', 'Woman', 'Egypt', 50),
 ('Claire', 'Liu', 'Woman', 'United States', 61),
 ('Leolia', 'Jeanjean', 'Woman', 'France', 120),
 ('Nuria', 'Parrizas Diaz', 'Woman', 'Spain', 72),
 ('Tessah', 'Andrianjafitrimo', 'Woman', 'France', 237),
 ('Oksana', 'Selekhmeteva', 'Woman', 'Russia', 179),
 ('Kamilla', 'Rakhimova', 'Woman', 'Russia', 93),
 ('Anna', 'Kalinskaya', 'Woman', 'Russia', 60),
 ('Taylor', 'Townsend', 'Woman', 'United States', 131),
 ('Katie', 'Volynets', 'Woman', 'United States', 112),
 ('Viktoriya', 'Tomova', 'Woman', 'Bulgaria', 90),
 ('Panna', 'Udvardy', 'Woman', 'Hungary', 77),
 ('Fernanda', 'Contreras Gomez', 'Woman', 'Mexico', 165),
 ('Rebecca', 'Sramkova', 'Woman', 'Sloveniavakia ', 313),
 ('Harriet', 'Dart', 'Woman', 'United Kingdom', 97),
 ('Valentini', 'Grammatikopoulou', 'Woman', 'Greece', 197),
 ('Daria', 'Saville', 'Woman', 'Australia', 54),
 ('Anna', 'Bondar', 'Woman', 'Hungary', 79),
 ('Magdalena', 'Frech', 'Woman', 'Poland', 116),
 ('Xinyu', 'Wang', 'Woman', 'China', 87),
 ('LIndiaa', 'Noskova', 'Woman', 'Czech Republic', 91),
 ('Emma', 'RaduCanadau', 'Woman', 'United Kingdom', 75),
 ('Reka-Luca', 'Jani', 'Woman', 'Hungary', 110),
 ('Ysaline', 'BonavenTurkeye', 'Woman', 'Belgium', 96),
 ('Mirjam', 'Bjorklund', 'Woman', 'Sweden', 157),
 ('Carole', 'Monnet', 'Woman', 'France', 225),
 ('Anastasia', 'Gasanova', 'Woman', 'Russia', 185),
 ('Elena-Gabriela', 'Russiae', 'Woman', 'Romania ', 102),
 ('Rebecca', 'Marino', 'Woman', 'Canada', 65),
 ('Alison-Van', 'Uytvanck', 'Woman', 'Belgium', 55),
 ('Beatriz', 'Haddad Maia', 'Woman', 'Brazil', 15),
 ('Cristina', 'Bucsa', 'Woman', 'Spain', 108),
 ('Kaia', 'Kane', 'Woman', 'Estonia', 30),
 ('Victoria', 'Azarenk', 'Woman', 'Belarus', 27),
 ('Olga', 'Danilovic', 'Woman', 'Sloveniavakia', 155),
 ('Dalma', 'Galfi', 'Woman', 'Hungary', 85),
 ('Jil', 'Teichmann', 'Woman', 'Swiss', 35),
 ('Tatjana', 'Mari', 'Woman', 'Germany', 70),
 ('Jule', 'Niemeier', 'Woman', 'Germany', 63),
 ('Timea', 'Babos', 'Woman', 'Hungary', 91),
 ('Coco', 'Vandeweghe', 'Woman', 'United States', 125),
 ('Yafan', 'Wang', 'Woman', 'China', 415),
 ('Kateryna', 'BaIndial', 'Woman', 'Ukraine', 111),
 ('Samantha', 'Murray Sharan', 'Woman', 'United Kingdom', 94),
 ('VItalialia', 'Diatchenko', 'Woman', 'Russia', 114),
 ('Bianca', 'Andreescu', 'Woman', 'Canada', 45),
 ('Amanda', 'Anisimova', 'Woman', 'United States', 23),
 ('Tsvetana', 'Pironkova', 'Woman', 'Bulgaria', -1),
 ('Aliona', 'Boliviasova', 'Woman', 'Spain', 55),
 ('Ellen', 'Peruez', 'Woman', 'Australia', 20),
 ('Francencesca', 'Jones', 'Woman', 'United Kingdom', -2),
 ('Kristie', 'Ahn', 'Woman', 'United States', -1),
 ('Mona', 'Barthel', 'Woman', 'Germany', 282),
 ('Jodie', 'Burrage', 'Woman', 'United Kingdom', 126),
 ('Katie', 'Swan', 'Woman', 'United Kingdom', 145),
 ('Vera', 'Zvonareva', 'Woman', 'Russia', 31),
 ('Lesley', 'Pattinama Kerkhove', 'Woman', 'Netherlands', 232),
 ('Samantha', 'Stosur', 'Woman', 'Australia', 114),
 ('Danielle', 'Lao', 'Woman', 'United States', 255),
 ('Katie', 'Boulter', 'Woman', 'United Kingdom', 132),
 ('Monica', 'Niculescu', 'Woman', 'Romania', 48),
 ('Jana', 'Fett', 'Woman', 'Croatia', 238),
 ('Sonay', 'Kartal', 'Woman', 'United Kingdom', 201),
 ('Catherine', 'Harrison', 'Woman', 'United States', 78),
 ('Emina', 'Bektas', 'Woman', 'United States', 103),
 ('Laura', 'Pigossi', 'Woman', 'Brazil', 118),
 ('Rebeka', 'Masarova', 'Woman', 'Spain', 135),
 ('Louisa', 'Chilerico', 'Woman', 'United States', 163),
 ('Kirsten', 'Flipkens', 'Woman', 'Belgium', 30),
 ('Jaimee', 'Fourlis', 'Woman', 'Australia', 167),
 ('Yue', 'Yuan', 'Woman', 'China', 74),
 ('Maja', 'Chwalinska', 'Woman', 'Poland', 160),
 ('Ylena', 'In-Albon', 'Woman', 'Swiss', 141),
 ('Yuriko-Lily', 'Miyazaki', 'Woman', 'United Kingdom', 215),
 ('Mai', 'Hontama', 'Woman', 'Japan', 205),
 ('Katarzyna', 'Kawa', 'Woman', 'Poland', 75),
 ('Zoe', 'Hives', 'Woman', 'Australia', 764),
 ('Tatjana', 'Maria', 'Woman', 'Germany', 70),
 ('Yanina', 'Wickmayer', 'Woman', 'Belgium', 158),
 ('Tamara', 'Koreanpatsch', 'Woman', 'Germany', 82),
 ('Maddison', 'Inglis', 'Woman', 'Australia', 182),
 ('Jamie', 'Loeb', 'Woman', 'United States', 234),
 ('Catherine', 'Mcnally', 'Woman', 'United States', 94),
 ('Ashlyn', 'KrueGermany', 'Woman', 'United States', 167),
 ('Alycia', 'Parks', 'Woman', 'United States', 73),
 ('Emma', 'Navarro', 'Woman', 'United States', 148),
 ('Sara', 'Errani', 'Woman', 'Italia', 106),
 ('Yaroslava', 'Shvedova', 'Woman', 'Kazakhstan', -1),
 ('Peyton', 'Stearns', 'Woman', 'United States', 212),
 ('LIndiaa', 'Fruhvirtova', 'Woman', 'Czech Republic', 78),
 ('Erika', 'Andreeva', 'Woman', 'Russia', 122),
 ('Daria', 'Snigur', 'Woman', 'Ukraine', 107),
 ('Eleana', 'Yu', 'Woman', 'United States', 653),
 ('Elizabeth', 'Mandlik', 'Woman', 'United States', 121),
 ('Viktoria', 'Kuzmova', 'Woman', 'Sloveniavakia', 85),
 ('Sara', 'Bejlek', 'Woman', 'Czech Republic', 178),
 ('Elina', 'Avanesyan', 'Woman', 'Russia', 137),
 ('Evgeniya', 'Rodina', 'Woman', 'Russia', 446),
 ('Jaqueline', 'Cristian', 'Woman', 'Romania', 149),
 ('Barbora', 'Strycova', 'Woman', 'Czech Republic', -1),
 ('Whitney', 'OSwissgwe', 'Woman', 'United States', 192),
 ('Arina', 'Rodionova', 'Woman', 'Australia', 255),
 ('Johanna', 'Konta', 'Woman', 'United Kingdom', -1),
 ('DEstoniaanee', 'Aiava', 'Woman', 'Australia', 279),
 ('Kimberly', 'Birrell', 'Woman', 'Australia', 171),
 ('Mayo', 'Hibi', 'Woman', 'Japan', 989),
 ('Valeria', 'Savinykh', 'Woman', 'Russia', 243),
 ('Lizette', 'Cabrera', 'Woman', 'Australia', 174),
 ('Arianne', 'Hartono', 'Woman', 'Netherlands', 153),
 ('Caroline', 'Dolehide', 'Woman', 'United States', 35),
 ('Su Jeong', 'Jang', 'Woman', 'Korean', 107),
 ('Robin', 'Anderson', 'Woman', 'United States', 192),
 ('Priscilla', 'Hon', 'Woman', 'Australia', 154);