DROP TABLE IF EXISTS P16_Player CASCADE;

CREATE TABLE IF NOT EXISTS P16_Player (
    Player_ID INT PRIMARY KEY AUTO_INCREMENT,
    Player_First_Name VARCHAR(32) NOT NULL,
    Player_Last_Name VARCHAR(32) NOT NULL,
    Player_Gender VARCHAR(8) CHECK (Player_Gender IN ("Man", "Woman")),
    Player_Nationality VARCHAR(32), -- NOT NULL,
    Player_ATP_Rank INT -- NOT NULL
);

INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Novak', 'Djokovic', 'Man', 'SRB', 5);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yoshihito', 'Nishioka', 'Man', 'JPN', 36);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'Molcan', 'Man', 'SVK', 50);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Coria', 'Man', 'ARG', 67);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aljaz', 'Bedene', 'Man', 'SLO', 345);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'O Connell', 'Man', 'AUS', 79);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Cuevas', 'Man', 'URU', 245);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jenson', 'Brooksby', 'Man', 'USA', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Grigor', 'Dimitrov', 'Man', 'BUL', 28);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'Giron', 'Man', 'USA', 61);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Coric', 'Man', 'CRO', 26);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Taberner', 'Man', 'ESP', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Altmaier', 'Man', 'GER', 77);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaume', 'Munar', 'Man', 'ESP', 57);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Kuznetsov', 'Man', 'RUS', 446);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzman', 'Man', 'ARG', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Felix', 'Auger-Aliassime', 'Man', 'CAN', 6);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Pablo', 'Varillas', 'Man', 'PER', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camilo', 'Ugo Carabelli', 'Man', 'ARG', 128);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aslan', 'Karatsev', 'Man', 'RUS', 59);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alessandro', 'Giannessi', 'Man', 'ITA', 268);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Gojo', 'Man', 'CRO', 145);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Filip', 'Krajinovic', 'Man', 'SRB', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Reilly', 'Opelka', 'Man', 'USA', 38);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Botic', 'Van de Zandschulp', 'Man', 'NED', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pavel', 'Kotov', 'Man', 'RUS', 99);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fabio', 'Fognini', 'Man', 'ITA', 56);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexei', 'Popyrin', 'Man', 'AUS', 121);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stan', 'Wawrinka', 'Man', 'SUI', 151);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Corentin', 'Moutet', 'Man', 'FRA', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jordan', 'Thompson', 'Man', 'AUS', 84);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rafael', 'Nadal', 'Man', 'ESP', 2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Zverev', 'Man', 'GER', 12);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Ofner', 'Man', 'AUT', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dusan', 'Lajovic', 'Man', 'SRB', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Baez', 'Man', 'ARG', 43);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brandon', 'Nakashima', 'Man', 'USA', 47);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kamil', 'Majchrzak', 'Man', 'POL', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tallon', 'Griekspoor', 'Man', 'NED', 96);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Davidovich Fokina', 'Man', 'ESP', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Isner', 'Man', 'USA', 41);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Quentin', 'Halys', 'Man', 'FRA', 64);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taro', 'Daniel', 'Man', 'JPN', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gregoire', 'Barrere', 'Man', 'FRA', 90);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Michael', 'Mmoh', 'Man', 'USA', 110);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernabe', 'Zapata Miralles', 'Man', 'ESP', 74);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Santiago', 'Rodriguez Taverna', 'Man', 'ARG', 175);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taylor', 'Fritz', 'Man', 'USA', 9);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cameron', 'Norrie', 'Man', 'GBR', 14);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Manuel', 'Guinard', 'Man', 'FRA', 148);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jason', 'Kubler', 'Man', 'AUS', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Kudla', 'Man', 'USA', 108);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Dellien', 'Man', 'BOL', 117);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominic', 'Thiem', 'Man', 'AUT', 106);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nuno', 'Borges', 'Man', 'POR', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karen', 'Khachanov', 'Man', 'RUS', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Korda', 'Man', 'USA', 34);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Millman', 'Man', 'AUS', 150);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lloyd', 'Harris', 'Man', 'RSA', 237);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Richard', 'Gasquet', 'Man', 'FRA', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Albert', 'Ramos-Vinolas', 'Man', 'ESP', 39);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thanasi', 'Kokkinakis', 'Man', 'AUS', 95);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Ignacio', 'Londero', 'Man', 'ARG', 238);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Alcaraz', 'Man', 'ESP', 1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Casper', 'Ruud', 'Man', 'NOR', 3);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jo-Wilfried', 'Tsonga', 'Man', 'FRA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emil', 'Ruusuvuori', 'Man', 'FIN', 40);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ugo', 'Humbert', 'Man', 'FRA', 87);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Joao', 'Sousa', 'Man', 'POR', 82);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chun-Hsin', 'Tseng', 'Man', 'TPE', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Peter', 'Gojowczyk', 'Man', 'GER', 233);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Sonego', 'Man', 'ITA', 45);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Frances', 'Tiafoe', 'Man', 'USA', 19);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benjamin', 'Bonzi', 'Man', 'FRA', 60);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Lehecka', 'Man', 'CZE', 81);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('David', 'Goffin', 'Man', 'BEL', 53);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'Cecchinato', 'Man', 'ITA', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Andujar', 'Man', 'ESP', 123);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Giulio', 'Zeppieri', 'Man', 'ITA', 162);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hubert', 'Hurkacz', 'Man', 'POL', 10);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Shapovalov', 'Man', 'CAN', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Holger', 'Rune', 'Man', 'DEN', 11);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Martinez', 'Man', 'ESP', 62);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Henri', 'Laaksonen', 'Man', 'SUI', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Norbert', 'Gombos', 'Man', 'SVK', 116);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Cachin', 'Man', 'ARG', 54);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Gaston', 'Man', 'FRA', 111);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'De Minaur', 'Man', 'AUS', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Evans', 'Man', 'GBR', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francisco', 'Cerundolo', 'Man', 'ARG', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Ymer', 'Man', 'SWE', 71);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('James', 'Duckworth', 'Man', 'AUS', 172);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lucas', 'Pouille', 'Man', 'FRA', 386);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zdenek', 'Kolar', 'Man', 'CZE', 249);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Musetti', 'Man', 'ITA', 23);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefanos', 'Tsitsipas', 'Man', 'GRE', 4);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Rublev', 'Man', 'RUS', 8);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Soonwoo', 'Kwon', 'Man', 'KOR', 83);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Adrian', 'Mannarino', 'Man', 'FRA', 46);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Delbonis', 'Man', 'ARG', 126);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benoit', 'Paire', 'Man', 'FRA', 180);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ilya', 'Ivashka', 'Man', 'BLR', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cristian', 'Garin', 'Man', 'CHI', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tommy', 'Paul', 'Man', 'USA', 33);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikoloz', 'Basilashvili', 'Man', 'GEO', 92);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maxime', 'Cressy', 'Man', 'USA', 32);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mackenzie', 'McDonald', 'Man', 'USA', 63);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Franco', 'Agamenone', 'Man', 'ITA', 139);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes Baena', 'Man', 'ESP', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oscar', 'Otte', 'Man', 'GER', 65);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bjorn', 'Fratangelo', 'Man', 'USA', 313);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jannik', 'Sinner', 'Man', 'ITA', 15);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Carreno Busta', 'Man', 'ESP', 13);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gilles', 'Simon', 'Man', 'FRA', 143);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Vesely', 'Man', 'CZE', 112);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Steve', 'Johnson', 'Man', 'USA', 113);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marton', 'Fucsovics', 'Man', 'HUN', 98);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Geoffrey', 'Blancaneaux', 'Man', 'FRA', 135);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Attila', 'Balazs', 'Man', 'HUN', 724);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marin', 'Cilic', 'Man', 'CRO', 17);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Miomir', 'Kecmanovic', 'Man', 'SRB', 29);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas Martin', 'Etcheverry', 'Man', 'ARG', 80);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'Rinderknech', 'Man', 'FRA', 44);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Bublik', 'Man', 'KAZ', 37);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ricardas', 'Berankis', 'Man', 'LTU', 168);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laslo', 'Djere', 'Man', 'SRB', 72);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Facundo', 'Bagnis', 'Man', 'ARG', 93);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniil', 'Medvedev', 'Man', 'RUS', 7);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tennys', 'Sandgren', 'Man', 'USA', 272);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Salvatore', 'Caruso', 'Man', 'ITA', 302);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefano', 'Travaglia', 'Man', 'ITA', 332);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yasutaka', 'Uchiyama', 'Man', 'JPN', 316);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Matteo', 'Berrettini', 'Man', 'ITA', 16);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Feliciano', 'Lopez', 'Man', 'ESP', 825);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kevin', 'Anderson', 'Man', 'RSA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andreas', 'Seppi', 'Man', 'ITA', 358);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mathias', 'Bourgue', 'Man', 'FRA', 410);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominik', 'Koepfer', 'Man', 'GER', 198);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Istomin', 'Man', 'UZB', 479);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roger', 'Federer', 'Man', 'SUI', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pierre-Hugues', 'Herbert', 'Man', 'FRA', 310);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gianluca', 'Mager', 'Man', 'ITA', 211);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gael', 'Monfils', 'Man', 'FRA', 52);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yen-hsun', 'Lu', 'Man', 'TPE', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschreiber', 'Man', 'GER', 418);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fernando', 'Verdasco', 'Man', 'ESP', 125);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jan-Lennard', 'Struff', 'Man', 'GER', 152);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roman', 'Safiullin', 'Man', 'RUS', 89);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kei', 'Nishikori', 'Man', 'JAP', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yannick', 'Hanfmann', 'Man', 'GER', 131);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mario', 'Vilella Martinez', 'Man', 'ESP', 657);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Bautista Agut', 'Man', 'ESP', 21);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'Cazaux', 'Man', 'FRA', 388);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikhail', 'Kukushkin', 'Man', 'KAZ', 223);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Radu', 'Albot', 'Man', 'MDA', 103);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeremy', 'Chardy', 'Man', 'FRA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maximilian', 'Marterer', 'Man', 'GER', 159);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Querrey', 'Man', 'USA', 326);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thiago', 'Monteiro', 'Man', 'BRA', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Egor', 'Gerasimov', 'Man', 'BLR', 279);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Enzo', 'Couacaud', 'Man', 'FRA', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Guido', 'Pella', 'Man', 'ARG', 759);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel Elahi', 'Galan', 'Man', 'COL', 69);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrej', 'Martin', 'Man', 'SVK', 330);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Tabilo', 'Man', 'CHI', 86);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Rosol', 'Man', 'CZE', 213);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tim', 'Van Rijthoven', 'Man', 'NED', 115);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andy', 'Murray', 'Man', 'GBR', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jay', 'Clarke', 'Man', 'GBR', 217);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christian', 'Harrison', 'Man', 'USA', 333);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrea', 'Vavassori', 'Man', 'ITA', 194);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ran', 'Peniston', 'Man', 'GBR', 144);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Heni', 'Laaksonen', 'Man', 'SUI', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Pucell', 'Man', 'AUS', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elias', 'Ymer', 'Man', 'SWE', 130);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc-Andrea', 'Huesler', 'Man', 'SUI', 58);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Grenier', 'Man', 'FRA', 142);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'De Minaur', 'Man', 'AUS', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zizou', 'Bergs', 'Man', 'BEL', 133);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'Draper', 'Man', 'GBR', 42);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Liam', 'Broady', 'Man', 'GBR', 164);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Klein', 'Man', 'AUT', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefan', 'Kozlov', 'Man', 'USA', 196);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzman', 'Man', 'ARG', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nicola', 'Kuhn', 'Man', 'GER', 503);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Paul', 'Jubb', 'Man', 'GBR', 219);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nick', 'Kyrgios', 'Man', 'AUS', 22);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes', 'Man', 'ESP', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Ritschard', 'Man', 'SUI', 169);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'Sock', 'Man', 'USA', 132);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dennis', 'Novak', 'Man', 'AUT', 181);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alastair', 'Gray', 'Man', 'GRB', 274);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chun Hsin', 'Tseng', 'Man', 'TPE', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Barrios Vera', 'Man', 'CHI', 230);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc', 'Polmans', 'Man', 'AUS', 335);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'Cecchinato', 'Man', 'ITA', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Vasek', 'Pospisil', 'Man', 'CAN ', 100);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jay', 'Clarke', 'Man', 'GBR', 217);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zhizhen', 'Zhang', 'Man', 'CHN ', 101);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Antoine', 'Hoang', 'Man', 'FRA ', 365);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschrei', 'Man', 'GER', 418);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Masur', 'Man', 'GER', 193);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yuichi', 'Sugita', 'Man', 'JPN ', 1136);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'Bolt', 'Man', 'AUS', 692);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Sousa', 'Man', 'POR', 525);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'Trungelliti', 'Man', 'ARG ', 225);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ben', 'Shelton', 'Man', 'USA ', 97);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yibing', 'Wu', 'Man', 'CHN', 119);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeffrey John', 'Wolf', 'Man', 'USA', 68);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emilio', 'Nava', 'Man', 'USA', 179);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nicolas', 'Jarry', 'Man', 'CHI', 141);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brandon', 'Holt', 'Man', 'USA', 216);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Machac', 'Man', 'CZE', 104);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kyle', 'Edmund', 'Man', 'GBR ', 583);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gijs', 'Brouwer', 'Man', 'NED ', 157);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'Eubanks', 'Man', 'USA ', 124);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Learner', 'Tien', 'Man', 'USA', 857);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rinky', 'Hijikata', 'Man', 'AUS', 166);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zachary', 'Svajda', 'Man', 'USA', 260);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Purcell', 'Man', 'AUS ', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ernesto', 'Escobedo', 'Man', 'USA', 227);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Shapocalov', 'Man', 'CAN', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ivo', 'Karlovic', 'Man', 'CRO ', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Evgeny', 'Donskoy', 'Man', 'RUS', 342);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cem', 'Ilkel', 'Man', 'TUR ', 343);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Riffice', 'Man', 'USA ', 494);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aleksandar', 'Vukic', 'Man', 'AUS', 140);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikola', 'Milojevic', 'Man', 'SRB ', 259);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Damir', 'Dzumhur', 'Man', 'BIH', 186);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Timofey', 'Skatov', 'Man', 'KAZ ', 146);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emilio', 'Gomez', 'Man', 'ECU', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Manuel', 'Cerundolo', 'Man', 'ARG', 154);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Milos', 'Raonic', 'Man', 'CAN', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sergiy', 'Stakhovsky', 'Man', 'UKR', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Frederico', 'Ferreira Silva', 'Man', 'POR', 244);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kimmer', 'Coppejans', 'Man', 'BEL ', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernard', 'Tomic', 'Man', 'AUS', 508);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cedrik-Marcel', 'Stebe', 'Man', 'GER', 203);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexandre', 'Muller', 'Man', 'FRA', 160);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrej', 'Martinez', 'Man', 'SVK', 330);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Li', 'Tu', 'Man', 'AUS', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Torpegaard', 'Man', 'DEN', 664);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Haase', 'Man', 'NED', 267);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sumit', 'Nagal', 'Man', 'IND', 502);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktor', 'Troicki', 'Man', 'SRB', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Li', 'Tu', 'Man', 'AUS', 199);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Torpegaard', 'Man', 'DEN', 664);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Haase', 'Man', 'NED', 267);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sumit', 'Nagal', 'Man', 'IND', 502);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktor', 'Troicki', 'Man', 'SRB', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ashleigh', 'Barty', 'Woman', 'AUS', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernarda', 'Pera', 'Woman', 'USA', 44);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Magda', 'Linette', 'Woman', 'POL', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chloe', 'Paquet', 'Woman', 'FRA', 163);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Irina', 'Bara', 'Woman', 'ROU', 173);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Astra', 'Sharma', 'Woman', 'AUS', 231);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yulia', 'Putintseva', 'Woman', 'KAZ', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ons', 'Jabeur', 'Woman', 'TUN', 2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cori', 'Gauff', 'Woman', 'USA', 7);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aleksandra', 'Krunic', 'Woman', 'SRB', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Qiang', 'Wang', 'Woman', 'CHN', 92);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Su-Wei', 'Hsieh', 'Woman', 'TPE', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('En-Shuo', 'Liang', 'Woman', 'TPE', 392);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fiona', 'Ferro', 'Woman', 'FRA ', 413);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasija', 'Sevastova', 'Woman', 'LAT', 681);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jennifer', 'Brady', 'Woman', 'USA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karolina', 'Pliskova', 'Woman', 'CZE', 32);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Donna', 'Vekic', 'Woman', 'CRO', 69);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carla', 'Suarez Navarro', 'Woman', 'ESP', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sloane', 'Stephens', 'Woman', 'USA', 37);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Varvara', 'Lepchenko', 'Woman', 'USA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Shuai', 'Zhang', 'Woman', 'CHN', 24);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrea', 'Petkovic', 'Woman', 'GER', 138);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karolina', 'Muchova', 'Woman', 'CZE', 153);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ekaterina', 'Alexandrova', 'Woman', 'RUS', 19);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Venus', 'Williams', 'Woman', 'USA ', 1017);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Barbora', 'Krejcikova', 'Woman', 'CZE', 21);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristyna', 'Pliskova', 'Woman', 'CZE', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ann', 'Li', 'Woman', 'USA', 133);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Margarita', 'Betova', 'Woman', 'RUS', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oceane', 'Babel', 'Woman', 'FRA', 453);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elina', 'Svitolina', 'Woman', 'UKR', 242);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sofia', 'Kenin', 'Woman', 'USA', 240);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jelena', 'Ostapenko', 'Woman', 'LAT', 18);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hailey', 'Baptiste', 'Woman', 'USA', 176);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Blinkova', 'Woman', 'RUS', 80);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tereza', 'Martincova', 'Woman', 'CZE ', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ivana', 'Jorovic', 'Woman', 'SRB', 496);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lin', 'Zhu', 'Woman', 'CHN', 64);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jessica', 'Pegula', 'Woman', 'USA', 3);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maria', 'Sakkari', 'Woman', 'GRE', 6);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katarina', 'Zavatska', 'Woman', 'UKR ', 307);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jasmine', 'Paolini', 'Woman', 'ITA ', 62);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefanie', 'Voegele', 'Woman', 'SUI', 245);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Heather', 'Watson', 'Woman', 'GBR ', 136);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zarina', 'Diyas', 'Woman', 'KAZ ', 1040);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Storm', 'Sanders', 'Woman', 'AUS', 243);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elise', 'Mertens', 'Woman', 'BEL', 29);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Garbine', 'Muguruza', 'Woman', 'ESP', 56);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marta', 'Kostyuk', 'Woman', 'UKR ', 71);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Saisai', 'Zheng', 'Woman', 'CHN', 396);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sara', 'Sorribes Tormo', 'Woman', 'ESP ', 67);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lara', 'Arruabarrera', 'Woman', 'ESP', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Varvara', 'Gracheva', 'Woman', 'RUS', 95);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camila', 'Giorgi', 'Woman', 'ITA ', 68);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Petra', 'Martic', 'Woman', 'CRO', 39);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anett', 'Kontaveit', 'Woman', 'EST', 17);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktorija', 'Golubic', 'Woman', 'SUI', 76);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna Karolina', 'Schmiedlova', 'Woman', 'GER', 99);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kristina', 'Mladenovic', 'Woman', 'FRA', 113);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Peterson', 'Woman', 'SWE', 134);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Shelby', 'Rogers', 'Woman', 'USA', 49);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaja', 'Juvan', 'Woman', 'SLO', 89);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Iga', 'Swiatek', 'Woman', 'POL ', 1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Serena', 'Williams', 'Woman', 'USA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Irina-Camelia', 'Begu', 'Woman', 'ROU', 34);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arantxa', 'Rus', 'Woman', 'NED ', 115);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mihaela', 'Buzarnescu', 'Woman', 'ROU', 391);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Danielle', 'Collins', 'Woman', 'USA ', 14);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Xiyu', 'Wang', 'Woman', 'CHN', 51);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anhelina', 'Kalinina', 'Woman', 'UKR ', 53);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Angelique', 'Kerber', 'Woman', 'GER', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena', 'Rybakina', 'Woman', 'KAZ', 22);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elsa', 'Jacquemot', 'Woman', 'FRA', 208);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nao', 'Hibino', 'Woman', 'JPN ', 139);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nina', 'Stojanovic', 'Woman', 'SRB', 439);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena', 'Vesnina', 'Woman', 'UKR', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Olga', 'Govortsova', 'Woman', 'BLR', 607);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Greet', 'Minnen', 'Woman', 'BEL', 206);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Petra', 'Kvitova', 'Woman', 'CZE', 16);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Victoria', 'Azarenka', 'Woman', 'BLR', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Svetlana', 'Kuznetsova', 'Woman', 'RUS', 177);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Clara', 'Tauson', 'Woman', 'DEN ', 127);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ekaterine', 'Gorgodze', 'Woman', 'GEO ', 221);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Leylah', 'Fernandez', 'Woman', 'CAN', 40);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Potapova', 'Woman', 'RUS', 43);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oceane', 'Dodin', 'Woman', 'FRA', 109);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Madison', 'Keys', 'Woman', 'USA', 11);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Pavlyuchenkova', 'Woman', 'RUS', 368);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christina', 'Mchale', 'Woman', 'USA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ajla', 'Tomljanovic', 'Woman', 'AUS', 33);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diane', 'Parry', 'Woman', 'FRA', 105);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aliaksandra', 'Sasnovich', 'Woman', 'BLR', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ana', 'Konjuh', 'Woman', 'CRO ', 117);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aryna', 'Sabalenka', 'Woman', 'BLR', 5);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tamara', 'Zidansek', 'Woman', 'SLO ', 86);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Madison', 'Brengle', 'Woman', 'USA', 59);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camila', 'Osorio', 'Woman', 'COL', 83);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marie', 'Bouzkova', 'Woman', 'CZE', 26);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katerina', 'Siniakova', 'Woman', 'CZE', 47);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Veronika', 'Kudermetova', 'Woman', 'RUS', 9);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Johanna', 'Kontaveit', 'Woman', 'GBR', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sorana', 'Cirstea', 'Woman', 'ROU', 38);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alison', 'Van Uytvanck', 'Woman', 'BEL', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Martina', 'Trevisan', 'Woman', 'ITA', 28);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Kasatkina', 'Woman', 'RUS', 8);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Misaki', 'Doi', 'Woman', 'JPN ', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nadia', 'Podoroska', 'Woman', 'ARG', 193);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Belinda', 'Bencic', 'Woman', 'SUI', 12);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kiki', 'Bertens', 'Woman', 'NED', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Polona', 'Hercog', 'Woman', 'SLO ', 414);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laura', 'Siegemund', 'Woman', 'GER', 172);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Caroline', 'Garcia', 'Woman', 'FRA', 4);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alizé', 'Cornet', 'Woman', 'FRA', 36);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Harmony', 'Tan', 'Woman', 'FRA', 146);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaia', 'Kanepi', 'Woman', 'EST', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marketa', 'Vondrousova', 'Woman', 'CZE', 98);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Paula', 'Badosa', 'Woman', 'ESP', 13);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lauren', 'Davis', 'Woman', 'USA', 88);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Clara', 'Burel', 'Woman', 'FRA', 128);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Danka', 'Kovinic', 'Woman', 'MNE', 57);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elisabetta', 'Cocciaretto', 'Woman', 'ITA', 66);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ana', 'Bogdan', 'Woman', 'ROU', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Patricia Maria', 'Tig', 'Woman', 'ROU', 792);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Naomi', 'Osaka', 'Woman', 'JPN ', 42);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Lesia', 'Tsurenko', 'Woman', 'UKR', 129);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Alison', 'Riske Amritraj', 'Woman', 'USA', 41);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Dayana', 'Yastremska', 'Woman', 'UKR', 101);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Kristina', 'Kucova', 'Woman', 'SVK ', 191);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Liudmila', 'Samsonova', 'Woman', 'RUS', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Simona', 'Halep', 'Woman', 'ROU', 10);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nastasja', 'Schunk', 'Woman', 'GER', 216);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maryna', 'Zanevska', 'Woman', 'BEL', 81);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Qinwen', 'Zheng', 'Woman', 'CHN', 25);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lucia', 'Bronzetti', 'Woman', 'ITA', 58);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mayar', 'Sherif', 'Woman', 'EGY', 50);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Claire', 'Liu', 'Woman', 'USA', 61);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Leolia', 'Jeanjean', 'Woman', 'FRA', 120);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nuria', 'Parrizas Diaz', 'Woman', 'ESP', 72);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tessah', 'Andrianjafitrimo', 'Woman', 'FRA', 237);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oksana', 'Selekhmeteva', 'Woman', 'RUS', 179);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kamilla', 'Rakhimova', 'Woman', 'RUS', 93);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Kalinskaya', 'Woman', 'RUS', 60);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taylor', 'Townsend', 'Woman', 'USA', 131);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katie', 'Volynets', 'Woman', 'USA', 112);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktoriya', 'Tomova', 'Woman', 'BUL', 90);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Panna', 'Udvardy', 'Woman', 'HUN', 77);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fernanda', 'Contreras Gomez', 'Woman', 'MEX', 165);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Sramkova', 'Woman', 'SVK ', 313);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Harriet', 'Dart', 'Woman', 'GBR', 97);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Valentini', 'Grammatikopoulou', 'Woman', 'GRE', 197);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Saville', 'Woman', 'AUS', 54);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anna', 'Bondar', 'Woman', 'HUN', 79);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Magdalena', 'Frech', 'Woman', 'POL', 116);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Xinyu', 'Wang', 'Woman', 'CHN', 87);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Linda', 'Noskova', 'Woman', 'CZE', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emma', 'Raducanu', 'Woman', 'GBR', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Reka-Luca', 'Jani', 'Woman', 'HUN', 110);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ysaline', 'Bonaventure', 'Woman', 'BEL', 96);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mirjam', 'Bjorklund', 'Woman', 'SWE', 157);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carole', 'Monnet', 'Woman', 'FRA', 225);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Anastasia', 'Gasanova', 'Woman', 'RUS', 185);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elena-Gabriela', 'Ruse', 'Woman', 'ROU ', 102);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebecca', 'Marino', 'Woman', 'CAN', 65);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alison-Van', 'Uytvanck', 'Woman', 'BEL', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Beatriz', 'Haddad Maia', 'Woman', 'BRA', 15);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cristina', 'Bucsa', 'Woman', 'ESP', 108);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kaia', 'Kane', 'Woman', 'EST', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Victoria', 'Azarenk', 'Woman', 'BLR', 27);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Olga', 'Danilovic', 'Woman', 'SVK', 155);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dalma', 'Galfi', 'Woman', 'HUN', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jil', 'Teichmann', 'Woman', 'SUI', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tatjana', 'Mari', 'Woman', 'GER', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jule', 'Niemeier', 'Woman', 'GER', 63);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Timea', 'Babos', 'Woman', 'HUN', 91);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Coco', 'Vandeweghe', 'Woman', 'USA', 125);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yafan', 'Wang', 'Woman', 'CHN', 415);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Kateryna', 'Baindl', 'Woman', 'UKR', 111);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Samantha', 'Murray Sharan', 'Woman', 'GBR', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Vitalia', 'Diatchenko', 'Woman', 'RUS', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Daria', 'Kasatkina', 'Woman', 'RUS', 8);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Bianca', 'Andreescu', 'Woman', 'CAN', 45);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Amanda', 'Anisimova', 'Woman', 'USA', 23);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Tsvetana', 'Pironkova', 'Woman', 'BUL', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Aliona', 'Bolsova', 'Woman', 'ESP', 55);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Ellen', 'Perez', 'Woman', 'AUS', 20);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Francesca', 'Jones', 'Woman', 'GBR', -2);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Kristie', 'Ahn', 'Woman', 'USA', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Mona', 'Barthel', 'Woman', 'GER', 282);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Jodie', 'Burrage', 'Woman', 'GBR', 126);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Katie', 'Swan', 'Woman', 'GBR', 145);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​Vera', 'Zvonareva', 'Woman', 'RUS', 31);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Lesley', 'Pattinama Kerkhove', 'Woman', 'NED', 232);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Samantha', 'Stosur', 'Woman', 'AUS', 114);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Danielle', 'Lao', 'Woman', 'USA', 255);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Katie', 'Boulter', 'Woman', 'GBR', 132);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Monica', 'Niculescu', 'Woman', 'ROU', 48);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jana', 'Fett', 'Woman', 'CRO', 238);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sonay', 'Kartal', 'Woman', 'GBR', 201);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Catherine', 'Harrison', 'Woman', 'USA', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emina', 'Bektas', 'Woman', 'USA', 103);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laura', 'Pigossi', 'Woman', 'BRA', 118);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rebeka', 'Masarova', 'Woman', 'ESP', 135);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Louisa', 'Chirico', 'Woman', 'USA', 163);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kirsten', 'Flipkens', 'Woman', 'BEL', 30);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaimee', 'Fourlis', 'Woman', 'AUS', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yue', 'Yuan', 'Woman', 'CHN', 74);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maja', 'Chwalinska', 'Woman', 'POL', 160);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ylena', 'In-Albon', 'Woman', 'SUI', 141);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yuriko-Lily', 'Miyazaki', 'Woman', 'GBR', 215);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mai', 'Hontama', 'Woman', 'JPN', 205);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Katarzyna', 'Kawa', 'Woman', 'POL', 75);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zoe', 'Hives', 'Woman', 'AUS', 764);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tatjana', 'Maria', 'Woman', 'GER', 70);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yanina', 'Wickmayer', 'Woman', 'BEL', 158);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tamara', 'Korpatsch', 'Woman', 'GER', 82);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maddison', 'Inglis', 'Woman', 'AUS', 182);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jamie', 'Loeb', 'Woman', 'USA', 234);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Catherine', 'Mcnally', 'Woman', 'USA', 94);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ashlyn', 'Krueger', 'Woman', 'USA', 167);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alycia', 'Parks', 'Woman', 'USA', 73);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emma', 'Navarro', 'Woman', 'USA', 148);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Sara', 'Errani', 'Woman', 'ITA', 106);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('​​Yaroslava', 'Shvedova', 'Woman', 'KAZ', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Peyton', 'Stearns', 'Woman', 'USA', 212);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Linda', 'Fruhvirtova', 'Woman', 'CZE', 78);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Erika', 'Andreeva', 'Woman', 'RUS', 122);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daria', 'Snigur', 'Woman', 'UKR', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Eleana', 'Yu', 'Woman', 'USA', 653);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elizabeth', 'Mandlik', 'Woman', 'USA', 121);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Viktoria', 'Kuzmova', 'Woman', 'SVK', 85);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sara', 'Bejlek', 'Woman', 'CZE', 178);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elina', 'Avanesyan', 'Woman', 'RUS', 137);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Evgeniya', 'Rodina', 'Woman', 'RUS', 446);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaqueline', 'Cristian', 'Woman', 'ROU', 149);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Barbora', 'Strycova', 'Woman', 'CZE', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Whitney', 'Osuigwe', 'Woman', 'USA', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arina', 'Rodionova', 'Woman', 'AUS', 255);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Johanna', 'Konta', 'Woman', 'GBR', -1);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Destanee', 'Aiava', 'Woman', 'AUS', 279);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kimberly', 'Birrell', 'Woman', 'AUS', 171);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mayo', 'Hibi', 'Woman', 'JPN', 989);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Valeria', 'Savinykh', 'Woman', 'RUS', 243);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lizette', 'Cabrera', 'Woman', 'AUS', 174);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arianne', 'Hartono', 'Woman', 'NED', 153);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Caroline', 'Dolehide', 'Woman', 'USA', 35);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Su Jeong', 'Jang', 'Woman', 'KOR', 107);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Robin', 'Anderson', 'Woman', 'USA', 192);
INSERT INTO P16_Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Priscilla', 'Hon', 'Woman', 'AUS', 154);
