DROP TABLE IF EXISTS Participate CASCADE;

CREATE TABLE IF NOT EXISTS Participate (
    Result VARCHAR(64) NOT NULL CHECK (Resault  IN ("1/64 Finalist", "1/32 Finalist", "1/16 Finalist", "1/8 Finalist", "1/4 Finalist", "1/2 Finalist", "Runner-up", "Champion")),
    Category VARCHAR(64) NOT NULL CHECK (Category IN ("Men’s Singles", "Women’s Singles", "Men’s Doubles", "Women’s Doubles", "Mixted Doubles")),
    _Year INT NOT NULL CHECK (_Year IN (2022, 2021)),
    GC_ID INT,
    Player_ID INT,
    FOREIGN KEY (GC_ID) REFERENCES Grand_Slam(GC_ID),
    FOREIGN KEY (Player_ID) REFERENCES Player(Player_ID),
    PRIMARY KEY(GC_ID, Player_ID, _Year)
);


INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (1, 1, 2022, 'Men’s Singles', '1/4 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (2, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (3, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (4, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (5, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (6, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (7, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (8, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (9, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (10, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (11, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (12, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (13, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (14, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (15, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (16, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (17, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (18, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (19, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (20, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (21, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (22, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (23, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (24, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (25, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (26, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (27, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (28, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (29, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (30, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (31, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (32, 1, 2022, 'Men’s Singles', 'Champion');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (33, 1, 2022, 'Men’s Singles', '1/2 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (34, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (35, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (36, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (37, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (38, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (39, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (40, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (41, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (42, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (43, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (44, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (45, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (46, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (47, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (48, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (49, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (50, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (51, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (52, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (53, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (54, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (55, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (56, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (57, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (58, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (59, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (60, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (61, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (62, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (63, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (64, 1, 2022, 'Men’s Singles', '1/4 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (65, 1, 2022, 'Men’s Singles', 'Runner-up');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (66, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (67, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (68, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (69, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (70, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (71, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (72, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (73, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (74, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (75, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (76, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (77, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (78, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (79, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (80, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (81, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (82, 1, 2022, 'Men’s Singles', '1/4 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (83, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (84, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (85, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (86, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (87, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (88, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (89, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (90, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (91, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (92, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (93, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (94, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (95, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (96, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (97, 1, 2022, 'Men’s Singles', '1/4 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (98, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (99, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (100, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (101, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (102, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (103, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (104, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (105, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (106, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (107, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (108, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (109, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (110, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (111, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (112, 1, 2022, 'Men’s Singles', '1/8 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (113, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (114, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (115, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (116, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (117, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (118, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (119, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (120, 1, 2022, 'Men’s Singles', '1/2 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (121, 1, 2022, 'Men’s Singles', '1/16 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (122, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (123, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (124, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (125, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (126, 1, 2022, 'Men’s Singles', '1/32 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (127, 1, 2022, 'Men’s Singles', '1/64 Finalist');
INSERT INTO Participate (Player_ID, GC_ID, _Year, Category, Result) VALUES (128, 1, 2022, 'Men’s Singles', '1/8 Finalist');
