DROP TABLE IF EXISTS Player CASCADE;

CREATE TABLE IF NOT EXISTS Player (
    Player_ID INT PRIMARY KEY AUTO_INCREMENT,
    Player_First_Name VARCHAR(32) NOT NULL,
    Player_Last_Name VARCHAR(32) NOT NULL,
    Player_Gender VARCHAR(8) CHECK (Player_Gender IN ("Man", "Woman")),
    Player_Nationality VARCHAR(32), -- NOT NULL,
    Player_ATP_Rank INT -- NOT NULL
);


INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Novak', 'Djokovic', 'Man', 'SRB', 5);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yoshihito', 'Nishioka', 'Man', 'JPN', 36);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'Molcan', 'Man', 'SVK', 50);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Coria', 'Man', 'ARG', 67);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aljaz', 'Bedene', 'Man', 'SLO', 345);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'Connell', 'Man', 'AUS', 79);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Cuevas', 'Man', 'URU', 245);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jenson', 'Brooksby', 'Man', 'USA', 48);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Grigor', 'Dimitrov', 'Man', 'BUL', 28);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'Giron', 'Man', 'USA', 61);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Coric', 'Man', 'CRO', 26);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Taberner', 'Man', 'ESP', 167);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Altmaier', 'Man', 'GER', 77);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jaume', 'Munar', 'Man', 'ESP', 57);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Kuznetsov', 'Man', 'RUS', 446);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzman', 'Man', 'ARG', 25);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Felix', 'Auger-Aliassime', 'Man', 'CAN', 6);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Pablo', 'Varillas', 'Man', 'PER', 107);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Camilo', 'Ugo Carabelli', 'Man', 'ARG', 128);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Aslan', 'Karatsev', 'Man', 'RUS', 59);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alessandro', 'Giannessi', 'Man', 'ITA', 268);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Borna', 'Gojo', 'Man', 'CRO', 145);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Filip', 'Krajinovic', 'Man', 'SRB', 55);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Reilly', 'Opelka', 'Man', 'USA', 38);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Botic', 'Van de Zandschulp', 'Man', 'NED', 35);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pavel', 'Kotov', 'Man', 'RUS', 99);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fabio', 'Fognini', 'Man', 'ITA', 56);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexei', 'Popyrin', 'Man', 'AUS', 121);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stan', 'Wawrinka', 'Man', 'SUI', 151);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Corentin', 'Moutet', 'Man', 'FRA', 51);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jordan', 'Thompson', 'Man', 'AUS', 84);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rafael', 'Nadal', 'Man', 'ESP', 2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Zverev', 'Man', 'GER', 12);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Ofner', 'Man', 'AUT', 192);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dusan', 'Lajovic', 'Man', 'SRB', 102);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Baez', 'Man', 'ARG', 43);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brandon', 'Nakashima', 'Man', 'USA', 47);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kamil', 'Majchrzak', 'Man', 'POL', 78);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tallon', 'Griekspoor', 'Man', 'NED', 96);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Davidovich Fokina', 'Man', 'ESP', 31);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Isner', 'Man', 'USA', 41);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Quentin', 'Halys', 'Man', 'FRA', 64);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taro', 'Daniel', 'Man', 'JPN', 94);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gregoire', 'Barrere', 'Man', 'FRA', 90);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Michael', 'Mmoh', 'Man', 'USA', 110);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bernabe', 'Zapata Miralles', 'Man', 'ESP', 74);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Santiago', 'Rodriguez Taverna', 'Man', 'ARG', 175);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Taylor', 'Fritz', 'Man', 'USA', 9);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cameron', 'Norrie', 'Man', 'GBR', 14);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Manuel', 'Guinard', 'Man', 'FRA', 148);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jason', 'Kubler', 'Man', 'AUS', 109);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Kudla', 'Man', 'USA', 108);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Dellien', 'Man', 'BOL', 117);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominic', 'Thiem', 'Man', 'AUT', 106);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nuno', 'Borges', 'Man', 'POR', 91);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Karen', 'Khachanov', 'Man', 'RUS', 20);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sebastian', 'Korda', 'Man', 'USA', 34);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('John', 'Millman', 'Man', 'AUS', 150);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lloyd', 'Harris', 'Man', 'RSA', 237);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Richard', 'Gasquet', 'Man', 'FRA', 70);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Albert', 'Ramos-Vinolas', 'Man', 'ESP', 39);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thanasi', 'Kokkinakis', 'Man', 'AUS', 95);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Juan Ignacio', 'Londero', 'Man', 'ARG', 238);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Carlos', 'Alcaraz', 'Man', 'ESP', 1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Casper', 'Ruud', 'Man', 'NOR', 3);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jo-Wilfried', 'Tsonga', 'Man', 'FRA', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emil', 'Ruusuvuori', 'Man', 'FIN', 40);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ugo', 'Humbert', 'Man', 'FRA', 87);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Joao', 'Sousa', 'Man', 'POR', 82);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chun-Hsin', 'Tseng', 'Man', 'TPE', 88);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Peter', 'Gojowczyk', 'Man', 'GER', 233);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Sonego', 'Man', 'ITA', 45);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Frances', 'Tiafoe', 'Man', 'USA', 19);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benjamin', 'Bonzi', 'Man', 'FRA', 60);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Lehecka', 'Man', 'CZE', 81);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('David', 'Goffin', 'Man', 'BEL', 53);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcos', 'Cecchinato', 'Man', 'ITA', 105);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Andujar', 'Man', 'ESP', 123);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Giulio', 'Zeppieri', 'Man', 'ITA', 162);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hubert', 'Hurkacz', 'Man', 'POL', 10);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Shapovalov', 'Man', 'CAN', 18);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Holger', 'Rune', 'Man', 'DEN', 11);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Martinez', 'Man', 'ESP', 62);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Henri', 'Laaksonen', 'Man', 'SUI', 171);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Norbert', 'Gombos', 'Man', 'SVK', 116);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Cachin', 'Man', 'ARG', 54);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Gaston', 'Man', 'FRA', 111);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'De Minaur', 'Man', 'AUS', 24);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Evans', 'Man', 'GBR', 27);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Francisco', 'Cerundolo', 'Man', 'ARG', 30);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikael', 'Ymer', 'Man', 'SWE', 71);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('James', 'Duckworth', 'Man', 'AUS', 172);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lucas', 'Pouille', 'Man', 'FRA', 386);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zdenek', 'Kolar', 'Man', 'CZE', 249);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lorenzo', 'Musetti', 'Man', 'ITA', 23);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefanos', 'Tsitsipas', 'Man', 'GRE', 4);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrey', 'Rublev', 'Man', 'RUS', 8);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Soonwoo', 'Kwon', 'Man', 'KOR', 83);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Adrian', 'Mannarino', 'Man', 'FRA', 46);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Federico', 'Delbonis', 'Man', 'ARG', 126);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Benoit', 'Paire', 'Man', 'FRA', 180);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ilya', 'Ivashka', 'Man', 'BLR', 75);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cristian', 'Garin', 'Man', 'CHI', 85);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tommy', 'Paul', 'Man', 'USA', 33);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikoloz', 'Basilashvili', 'Man', 'GEO', 92);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maxime', 'Cressy', 'Man', 'USA', 32);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mackenzie', 'McDonald', 'Man', 'USA', 63);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Franco', 'Agamenone', 'Man', 'ITA', 139);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes Baena', 'Man', 'ESP', 76);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Oscar', 'Otte', 'Man', 'GER', 65);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Bjorn', 'Fratangelo', 'Man', 'USA', 313);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jannik', 'Sinner', 'Man', 'ITA', 15);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pablo', 'Carreno Busta', 'Man', 'ESP', 13);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gilles', 'Simon', 'Man', 'FRA', 143);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jiri', 'Vesely', 'Man', 'CZE', 112);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Steve', 'Johnson', 'Man', 'USA', 113);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marton', 'Fucsovics', 'Man', 'HUN', 98);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Geoffrey', 'Blancaneaux', 'Man', 'FRA', 135);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Attila', 'Balazs', 'Man', 'HUN', 724);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marin', 'Cilic', 'Man', 'CRO', 17);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Miomir', 'Kecmanovic', 'Man', 'SRB', 29);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas Martin', 'Etcheverry', 'Man', 'ARG', 80);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'Rinderknech', 'Man', 'FRA', 44);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Bublik', 'Man', 'KAZ', 37);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ricardas', 'Berankis', 'Man', 'LTU', 168);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Laslo', 'Djere', 'Man', 'SRB', 72);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Facundo', 'Bagnis', 'Man', 'ARG', 93);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniil', 'Medvedev', 'Man', 'RUS', 7);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tennys', 'Sandgren', 'Man', 'USA', 272);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Salvatore', 'Caruso', 'Man', 'ITA', 302);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefano', 'Travaglia', 'Man', 'ITA', 332);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yasutaka', 'Uchiyama', 'Man', 'JPN', 316);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Matteo', 'Berrettini', 'Man', 'ITA', 16);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Feliciano', 'Lopez', 'Man', 'ESP', 825);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kevin', 'Anderson', 'Man', 'RSA', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andreas', 'Seppi', 'Man', 'ITA', 358);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mathias', 'Bourgue', 'Man', 'FRA', 410);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dominik', 'Koepfer', 'Man', 'GER', 198);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Istomin', 'Man', 'UZB', 479);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roger', 'Federer', 'Man', 'SUI', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pierre-Hugues', 'Herbert', 'Man', 'FRA', 310);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gianluca', 'Mager', 'Man', 'ITA', 211);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gael', 'Monfils', 'Man', 'FRA', 52);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yen-hsun', 'Lu', 'Man', 'TPE', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschreiber', 'Man', 'GER', 418);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fernando', 'Verdasco', 'Man', 'ESP', 125);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jan-Lennard', 'Struff', 'Man', 'GER', 152);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roman', 'Safiullin', 'Man', 'RUS', 89);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kei', 'Nishikori', 'Man', 'JAP', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yannick', 'Hanfmann', 'Man', 'GER', 131);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mario', 'Vilella Martinez', 'Man', 'ESP', 657);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Bautista Agut', 'Man', 'ESP', 21);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Arthur', 'Cazaux', 'Man', 'FRA', 388);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Mikhail', 'Kukushkin', 'Man', 'KAZ', 223);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Radu', 'Albot', 'Man', 'MDA', 103);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeremy', 'Chardy', 'Man', 'FRA', -1);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Maximilian', 'Marterer', 'Man', 'GER', 159);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Querrey', 'Man', 'USA', 326);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Thiago', 'Monteiro', 'Man', 'BRA', 73);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Egor', 'Gerasimov', 'Man', 'BLR', 279);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Enzo', 'Couacaud', 'Man', 'FRA', 174);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Guido', 'Pella', 'Man', 'ARG', 759);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel Elahi', 'Galan', 'Man', 'COL', 69);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrej', 'Martin', 'Man', 'SVK', 330);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Tabilo', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nikoloz', 'Basilashvi', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Rosol', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tim', 'Van Rijtho', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andy', 'Murray', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('James', 'Clarke', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christian', 'Harrison', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Etcheverry', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Frances', 'Taifoe', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Andrea', 'Vavassori', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ran', 'Peniston', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Heni', 'Laaksonen', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Pucell', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alejandro', 'Davidovich', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Elias', 'Ymer', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc-Andrea', 'Huesler', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Hugo', 'Grenier', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'De Minaur', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zizou', 'Begs', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'Draper', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Liam', 'Broady', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Lukas', 'Klein', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Stefan', 'Kozlov', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Diego', 'Schwartzma', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nicola', 'Kuhn', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Paul', 'Jubb', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nick', 'Kyrgios', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Roberto', 'Carballes', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alexander', 'Ritschard', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jack', 'Sock', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Dennis', 'Novak', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Facundo', 'Facundo', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alastair', 'Gray', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Chun Hsin', 'Tseng', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marcelo', 'Barrios Vera', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marc', 'Polmans', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'Cecchinato', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Vasek', 'Pospisil', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jay', 'Clarke', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zhizhen', 'Zhang', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Antoine', 'Hoang', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Philipp', 'Kohlschrei', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Daniel', 'Masur', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yuichi', 'Sugita', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Alex', 'Bolt', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Pedro', 'Sousa', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Marco', 'Trungelliti', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ben', 'Shelton', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Yibing', 'Wu', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Jeffrey John', 'Wolf', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Emilio', 'Nava', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Nicolas', 'Jarry', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Brandon', 'Holt', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Tomas', 'Machac', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Kyle', 'Edmund', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Gijs', 'Brouwer', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Christopher', 'Eubanks', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Learner', 'Tien', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Rinky', 'Hijikata', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Fabio', 'Gognini', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Zachary', 'Svajda', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Max', 'Purcell', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ernesto', 'Escobedo', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Denis', 'Shapocalov', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Ivo', 'Karlovic', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Evgeny', 'Donskoy', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Cem', 'Ilkel', 'Man', 'INC', -2);
INSERT INTO Player (Player_First_Name, Player_Last_Name, Player_Gender, Player_Nationality, Player_ATP_Rank) VALUES ('Sam', 'Riffice', 'Man', 'INC', -2);
